/*
 * File: app/view/ActivityCarRequestPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.ActivityCarRequestPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.activitycarrequestpanel',

    onAddBtnClick: function(button, e, eOpts) {
        var activityCarRequestPanel=button.up('#ActivityCarRequestPanel');

        var carbrandid = activityCarRequestPanel.down('#carBrand').getValue();
        var carsetid = activityCarRequestPanel.down('#carset').getValue();
        var vid = activityCarRequestPanel.down('#carType').getValue();
        var color = activityCarRequestPanel.down('#carColor').getValue();
        var lessprice = activityCarRequestPanel.down('#lesspriceField').getValue();
        var acid = activityCarRequestPanel.acid;
        var stid = activityCarRequestPanel.stid;

        if(carsetid===null || lessprice===null){
            Ext.Msg.alert('提示','请填写必要信息!');
            return;
        }

        var data = {
            'carbrandid':carbrandid,
            'carsetid':carsetid,
            'vid':vid,
            'color':color,
            'lessprice':lessprice,
            'acid':acid,
            'stid':stid
        };

        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

        Ext.Ajax.request({
            headers:{'Content-Type':'application/json'},
            url: url + '/biz/app/salesvehicle/add.do',
            params: JSON.stringify(data),
            success: function (response) {
                var text = response.responseText;
                var result = JSON.parse(text);
                if (result === null) {
                    Ext.Msg.alert('提示', '添加出错了，结果：' + text);
                    return;
                }

                if (result.succeed === true) {
                    Ext.getStore('ActivityCarStore').reload();
                    Ext.Msg.alert('提示', '添加成功');
                } else {
                    Ext.Msg.alert('提示', '添加出错了，错误：' + result.errMsg);
                }
            }
        });
    },

    onCarBrandSelect: function(combo, records, eOpts) {
        var brandId=records[0].data.id;

        var carsetStore=Ext.getStore('CarsetStore');

        var ajaxProxy=carsetStore.getProxy();

        var url=Ext.getStore('ConfigStore').getAt(0).get('CarBrandServerUrl');
        ajaxProxy.setUrl(url + "/car/queryCarset?id="+brandId);
        carsetStore.load();
    },

    onCarsetSelect: function(combo, records, eOpts) {
        var activityCarRequestPanel=combo.up('#ActivityCarRequestPanel');
        var type = activityCarRequestPanel.type;
        var carTypeStore=Ext.getStore('CarTypeStore');

        if(type===1){
            var carsetId=records[0].data.id;
            if(carsetId===0){
                return;
            }

            var ajaxProxy=carTypeStore.getProxy();

            var url=Ext.getStore('ConfigStore').getAt(0).get('CarBrandServerUrl');
            ajaxProxy.setUrl(url + "/car/queryCar?id="+carsetId);
            carTypeStore.load();
        }else{
            carTypeStore.removeAll();
            carTypeStore.load();
        }
    },

    onCarTypeSelect: function(combo, records, eOpts) {
        var carTypeId=records[0].data.id;
        if(carTypeId===null){
            return;
        }

        var CarColorStore=Ext.getStore('CarColorStore');
        var ajaxProxy=CarColorStore.getProxy();

        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderServerUrl');
        ajaxProxy.setUrl(url + "/hg/carenquiry/color/get.do?cartypeid="+carTypeId);
        CarColorStore.load();
    },

    onActivityRequestPanelBeforeRender: function(component, eOpts) {
        var carBrandStore = Ext.getStore('CarBrandStord');

        if(carBrandStore.data.length>0){/**carBrandStore中已有数据***/
            return;
        }

        var ajaxProxy = carBrandStore.getProxy();
        var url = Ext.getStore('ConfigStore').getAt(0).get('CarBrandServerUrl');
        ajaxProxy.setUrl(url + "/car/queryBrand");
        carBrandStore.load();
    }

});
