/*
 * File: app/view/ActivityManagePanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.ActivityManagePanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.activitymanagepanel',

    onSystemSelectorSelect: function (combo, records, eOpts) {
        var activityManagePanel = Ext.getCmp('ActivityManagePanel');
        var systemSelector = activityManagePanel.down('#systemSelector');
        var systemId = systemSelector.getValue();

        if (systemId === null) {
            return;
        }

        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

        var activityStore = Ext.getStore('ActivityStore');
        var ajaxProxyOn = activityStore.getProxy();
        ajaxProxyOn.setUrl(url + "/biz/app/activities/get.do?" + "appId=" + systemId);
        activityStore.reload();
    },

    onSystemSelectorBeforeRender: function (component, eOpts) {
        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

        var businessSystemManagerStore = Ext.getStore('BusinessSystemManagerStore');

        var ajaxProxy = businessSystemManagerStore.getProxy();

        ajaxProxy.setUrl(url + "/biz/app/list.do");

        businessSystemManagerStore.load();
    },

    onAddBtnClick: function (button, e, eOpts) {
        var activityRequestPanel = new CallCenterApp.view.ActivityRequestPanel({});

        var myForm = new Ext.window.Window({
            modal: true,
            autoScroll: true,
            title: '活动添加',
            width: 520,
            height: 370
        });

        myForm.add(activityRequestPanel);
        myForm.show();
    },

    onActivityGridPanelRowClick: function (tableview, record, tr, rowIndex, e, eOpts) {
        var systemId = record.data.stid;
        var actId = record.data.acid;

        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

        var activityCarStore = Ext.getStore('ActivityCarStore');
        var ajaxProxyOn = activityCarStore.getProxy();
        ajaxProxyOn.setUrl(url + "/biz/app/salesvehicle/get.do?" + "appId=" + systemId + "&actId=" + actId);
        activityCarStore.reload();
    }

});
