/*
 * File: app/view/BannerManagePanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.BannerManagePanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.bannermanagepanel',

    onSystemSelectorSelect: function (combo, records, eOpts) {
        var bannerManagePanel = Ext.getCmp('BannerManagePanel');
        var systemSelector = bannerManagePanel.down('#systemSelector');
        var systemId = systemSelector.getValue();

        if (systemId === null) {
            return;
        }

        var bannerManageStore = Ext.getStore('BannerManageStore');
        var ajaxProxy = bannerManageStore.getProxy();
        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

        ajaxProxy.setUrl(url + "/biz/app/banner/get.do?" + "appId=" + systemId);
        bannerManageStore.load();

    },

    onBannerManageGridPanelRowDblClick: function (tableview, record, tr, rowIndex, e, eOpts) {
        var bannerManagePanel = Ext.getCmp('BannerManagePanel');
        var bannerManageGridPanel = bannerManagePanel.down('#BannerManageGridPanel');

        if (bannerManageGridPanel.selection === null) {
            return;
        }

        var data = record.data;
        var image = data.image;
        if (image === null) {
            image = "";
        }
        var bannerImg = bannerManagePanel.down('#BannerImg');
        bannerImg.setSrc(image);
        bannerManagePanel.down('#id').setValue(data.bnid);
        bannerManagePanel.down('#orderField').setValue(data.order);
        bannerManagePanel.down('#urlField').setValue(data.url);
        bannerManagePanel.down('#docSelector').setValue(data.aid);
        bannerManagePanel.down('#descField').setValue(data.desc);

        bannerManagePanel.down('#saveBtn').setDisabled(false);
    },

    onImageFieldUploadFiledRender: function (component, eOpts) {
        var bannerManagePanel = component.up('#BannerManagePanel');

        var bannerImg = bannerManagePanel.down('#BannerImg');
        var fileuploadProgressBar = bannerManagePanel.down('#fileuploadProgressBar');


        var url = 'http://113.247.237.98:10002/upload?dir=dasheng';

        $('#imageUploadFiled-button-fileInputEl').fileupload({
            url: url,
            dataType: 'json',
            acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
            done: function (e, data) {
                $.each(data.result.files, function (index, file) {

                    bannerImg.setSrc(file.url);

                });
            },
            progressall: function (e, data) {
                var progress = parseInt(data.loaded / data.total * 100, 10);
                fileuploadProgressBar.setValue(progress / 100);

            }
        }).prop('disabled', !$.support.fileInput)
            .parent().addClass($.support.fileInput ? undefined : 'disabled');
    },

    onAddBtnClick: function (button, e, eOpts) {
        var bannerManagePanel = button.up('#BannerManagePanel');

        var bannerManageGridPanel = bannerManagePanel.down('#BannerManageGridPanel');

        var bannerImg = bannerManagePanel.down('#BannerImg');

        var systemSelector = bannerManagePanel.down('#systemSelector');
        var systemId = systemSelector.getValue();

        if (systemId === null) {
            Ext.Msg.alert('提示', '未选择系统！！！');
            return;
        }

        var src = bannerImg.src;
        var order = bannerManagePanel.down('#orderField').getValue();
        var url = bannerManagePanel.down('#urlField').getValue();
        var doc = bannerManagePanel.down('#docSelector').getValue();
        var desc = bannerManagePanel.down('#descField').getValue();

        var LoginSuccessStore = Ext.getStore('LoginSuccessJsonStore');
        var userId = LoginSuccessStore.data.items[0].data.userId;

        var data = {
            image: src,
            url: url,
            aid: doc,
            order: order,
            editorid: userId,
            stid: systemId,
            desc: desc

        };
        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');
        Ext.Ajax.request({

            headers: {'Content-Type': 'application/json'},
            url: url + '/biz/app/banner/add.do',
            params: JSON.stringify(data),
            success: function (response) {
                var text = response.responseText;
                var result = JSON.parse(text);
                if (result === null) {
                    Ext.Msg.alert('提示', '添加出错了，结果：' + text);
                    return;
                }


                if (result.succeed === true) {
                    Ext.Msg.alert('提示', '添加成功');
                    var bannerManageStore = Ext.getStore('BannerManageStore');
                    bannerManageStore.load();

                } else {
                    Ext.Msg.alert('提示', '添加出错了，错误：' + result.errMsg);
                }
            }
        });
    },

    onSaveBtnClick: function (button, e, eOpts) {
        var bannerManagePanel = button.up('#BannerManagePanel');

        var id = bannerManagePanel.down('#id').getValue();
        var bannerImg = bannerManagePanel.down('#BannerImg');
        var src = bannerImg.src;
        var order = bannerManagePanel.down('#orderField').getValue();
        var url = bannerManagePanel.down('#urlField').getValue();
        var doc = bannerManagePanel.down('#docSelector').getValue();
        var desc = bannerManagePanel.down('#descField').getValue();

        var data = {
            bnid: id,
            image: src,
            url: url,
            aid: doc,
            order: order,
            desc: desc

        };
        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');
        Ext.Ajax.request({

            headers: {'Content-Type': 'application/json'},
            url: url + '/biz/app/banner/update.do',
            params: JSON.stringify(data),
            success: function (response) {
                var text = response.responseText;
                var result = JSON.parse(text);
                if (result === null) {
                    Ext.Msg.alert('提示', '保存出错了，结果：' + text);
                    return;
                }


                if (result.succeed === true) {
                    Ext.Msg.alert('提示', '保存成功');
                    var bannerManageStore = Ext.getStore('BannerManageStore');
                    bannerManageStore.load();

                } else {
                    Ext.Msg.alert('提示', '保存出错了，错误：' + result.errMsg);
                }
            }
        });

    },

    onBannerManagePanelBeforeRender: function (component, eOpts) {
        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

        var businessSystemManagerStore = Ext.getStore('BusinessSystemManagerStore');

        var ajaxProxy = businessSystemManagerStore.getProxy();

        ajaxProxy.setUrl(url + "/biz/app/list.do");

        businessSystemManagerStore.load();
    }

});
