/*
 * File: app/view/CarsetImagAddPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.CarsetImagAddPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.carsetimagaddpanel',

    onCarbrandSelectSelect: function(combo, records, eOpts) {
        var brandId=records[0].data.id;

        var carMenuStore=Ext.getStore('CarMenuStore');

        var ajaxProxy=carMenuStore.getProxy();

        var url=Ext.getStore('ConfigStore').getAt(0).get('NewCarshopServerUrl');
        ajaxProxy.setUrl(url + "/services/auto/brand/"+brandId+"/manu");
        carMenuStore.load();
    },

    onCarfirmsSelectSelect: function(combo, records, eOpts) {
        var menuId=records[0].data.id;

        var systemConfigStore=Ext.getStore('SystemConfigStore');
        var systemId=systemConfigStore.getAt(0).get('systemId');

        var newCarsetStore=Ext.getStore('NewCarsetStore');
        var ajaxProxy=newCarsetStore.getProxy();
        var url=Ext.getStore('ConfigStore').getAt(0).get('NewCarshopServerUrl');

        ajaxProxy.setUrl(url + "/services/auto/manu/"+menuId+"/carset/system/"+systemId);
        newCarsetStore.load();
    },

    onCarsetImagAddGridPanelRender: function(component, eOpts) {
        var carBrandStore = Ext.getStore('CarBrandStord');

        if(carBrandStore.data.length>0){
            return;
        }
        var ajaxProxy = carBrandStore.getProxy();
        var url = Ext.getStore('ConfigStore').getAt(0).get('CarBrandServerUrl');
        ajaxProxy.setUrl(url + "/car/queryBrand");
        carBrandStore.load();
    },

    onCarsetImagAddGridPanelSelectionChange: function(model, selected, eOpts) {
        var imageContent=Ext.getCmp('carsetImagContent');
        var image=selected[0].data.image;
        imageContent.setSrc(image);
    },

    onImageUploadFiledRender: function(component, eOpts) {
        var carsetImagAddpanel=component.up('#carsetImagAddpanel');

        var carsetImagAddGridPanel=carsetImagAddpanel.down('#carsetImagAddGridPanel');
        var carsetImageContent=carsetImagAddpanel.down('#carsetImagContent');
        var fileuploadProgressBar=carsetImagAddpanel.down('#fileuploadProgressBar');


        var url =  'http://localhost:8480/upload?dir=dasheng';

        $('#imageFiled-button-fileInputEl').fileupload({
            url: url,
            dataType: 'json',
            acceptFileTypes:  /(\.|\/)(gif|jpe?g|png)$/i,
            done: function (e, data) {
                $.each(data.result.files, function (index, file) {

                    carsetImageContent.setSrc(file.url);

                });
            },
            progressall: function (e, data) {
                var progress = parseInt(data.loaded / data.total * 100, 10);
                fileuploadProgressBar.setValue(progress/100);

            }
        }).prop('disabled', !$.support.fileInput)
        .parent().addClass($.support.fileInput ? undefined : 'disabled');
    },

    onUpdateSaveBtnClick: function(button, e, eOpts) {
        var carsetImagAddpanel=button.up('#carsetImagAddpanel');

        var carsetImagAddGridPanel=carsetImagAddpanel.down('#carsetImagAddGridPanel');

        var imageFiled=carsetImagAddpanel.down('#imageFiled');

        var carsetImagContent=carsetImagAddpanel.down('#carsetImagContent');

        var carfirmsSelect=carsetImagAddpanel.down('#carfirmsSelect');


        var selectedRecords=carsetImagAddGridPanel.selModel.selected.items;

        if(selectedRecords.length<1){
            Ext.Msg.alert('提示','未选择车系信息，请确认！！！');
            return;
        }

        var carsetId=selectedRecords[0].data.id;

        var src=carsetImagContent.src;

        var data={
            id:carsetId,
            modelsImage:src,
            stid:'1001'

        };
        var url = Ext.getStore('ConfigStore').getAt(0).get('NewCarshopServerUrl');
        Ext.Ajax.request({

            headers:{'Content-Type':'application/json'},
            url: url + '/services/auto/carset',
            params: JSON.stringify(data),
            success: function (response) {
                var text = response.responseText;
                var result = JSON.parse(text);
                if (result === null) {
                    Ext.Msg.alert('提示', '保存出错了，结果：' + text);
                    return;
                }

                if (result.succeed === true) {
                    Ext.Msg.alert('提示', '保存成功');


                    var menuId=carfirmsSelect.value;
                    var newCarsetStore=Ext.getStore('NewCarsetStore');
                    var ajaxProxy=newCarsetStore.getProxy();
                    var url=Ext.getStore('ConfigStore').getAt(0).get('NewCarshopServerUrl');

                    ajaxProxy.setUrl(url + "/services/auto/manu/"+menuId+"/carset/system/1001");
                    newCarsetStore.load();



                } else {
                    Ext.Msg.alert('提示', '保存出错了，错误：' + result.errMsg);
                }
            }
        });
    }

});
