/*
 * File: app/view/hgBusinessViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.hgBusinessViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.hgbusiness',

    onMenuHgClick: function (menu, item, e, eOpts) {
        var mainView = Ext.getCmp('mainView');
        var contentPanel = mainView.getComponent('contentPanel');

        if (item.itemId == 'hgRequestItem') {
            var hgRequestPanel = contentPanel.getComponent('hgRequestPanel');

            if (hgRequestPanel === undefined) {
                hgRequestPanel = new CallCenterApp.view.HgRequestPanel({});

                contentPanel.add(hgRequestPanel);
            }

            contentPanel.setActiveTab(hgRequestPanel);
        } else if (item.itemId == 'hgStatusItem') {
            var hgStatusPanel = contentPanel.getComponent('hgStatusPanel');

            if (hgStatusPanel === undefined) {
                hgStatusPanel = new CallCenterApp.view.HgStatusPanel({});

                contentPanel.add(hgStatusPanel);
            }

            contentPanel.setActiveTab(hgStatusPanel);
        } else if (item.itemId == 'hgQuestionsItem') {
            var HgQuestionMagPanel = contentPanel.getComponent('HgQuestionMagPanel');

            if (HgQuestionMagPanel === undefined) {
                HgQuestionMagPanel = new CallCenterApp.view.HgQuestionMagPanel({});

                contentPanel.add(HgQuestionMagPanel);
            }
            contentPanel.setActiveTab(HgQuestionMagPanel);
        }
    }

});
