/*
 * File: app/view/InsuranceRequestPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.InsuranceRequestPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.insurancerequestpanel',

    onCdwMoneyBlur: function (component, event, eOpts) {
        var insurancerequestpanel = component.up('#insurancerequestpanel');
        var cdwMoneyField = insurancerequestpanel.down('#cdwMoney');
        var tpliMoneyField = insurancerequestpanel.down('#tpliMoney');
        var dsiMoneyFiled = insurancerequestpanel.down('#dsiMoney');
        var psiMoneyFiled = insurancerequestpanel.down('#psiMoney');
        var theftfeeFiled = insurancerequestpanel.down('#theftfee');
        var domesticglassfeeFiled = insurancerequestpanel.down('#domesticglassfee');
        var importglassfee = insurancerequestpanel.down('#importglassfee');
        var repairdepotfeeFiled = insurancerequestpanel.down('#repairdepotfee');
        var abatementfeeFiled = insurancerequestpanel.down('#abatementfee');

        var insurancefeeFiled = insurancerequestpanel.down('#insurancefee');

        insurancefeeFiled.setValue(component.getValue() + tpliMoneyField.getValue() +
        dsiMoneyFiled.getValue() + psiMoneyFiled.getValue() +
        theftfeeFiled.getValue() + domesticglassfeeFiled.getValue() +
        importglassfee.getValue() + repairdepotfeeFiled.getValue() +
        abatementfeeFiled.getValue());
    },

    onTpliMoneyBlur: function (component, event, eOpts) {
        var insurancerequestpanel = component.up('#insurancerequestpanel');
        var cdwMoneyField = insurancerequestpanel.down('#cdwMoney');
        var tpliMoneyField = insurancerequestpanel.down('#tpliMoney');
        var dsiMoneyFiled = insurancerequestpanel.down('#dsiMoney');
        var psiMoneyFiled = insurancerequestpanel.down('#psiMoney');
        var theftfeeFiled = insurancerequestpanel.down('#theftfee');
        var domesticglassfeeFiled = insurancerequestpanel.down('#domesticglassfee');
        var importglassfee = insurancerequestpanel.down('#importglassfee');
        var repairdepotfeeFiled = insurancerequestpanel.down('#repairdepotfee');
        var abatementfeeFiled = insurancerequestpanel.down('#abatementfee');

        var insurancefeeFiled = insurancerequestpanel.down('#insurancefee');

        insurancefeeFiled.setValue(cdwMoneyField.getValue() + tpliMoneyField.getValue() +
        dsiMoneyFiled.getValue() + psiMoneyFiled.getValue() +
        theftfeeFiled.getValue() + domesticglassfeeFiled.getValue() +
        importglassfee.getValue() + repairdepotfeeFiled.getValue() +
        abatementfeeFiled.getValue());
    },

    onDsiMoneyBlur: function (component, event, eOpts) {
        var insurancerequestpanel = component.up('#insurancerequestpanel');
        var cdwMoneyField = insurancerequestpanel.down('#cdwMoney');
        var tpliMoneyField = insurancerequestpanel.down('#tpliMoney');
        var dsiMoneyFiled = insurancerequestpanel.down('#dsiMoney');
        var psiMoneyFiled = insurancerequestpanel.down('#psiMoney');
        var theftfeeFiled = insurancerequestpanel.down('#theftfee');
        var domesticglassfeeFiled = insurancerequestpanel.down('#domesticglassfee');
        var importglassfee = insurancerequestpanel.down('#importglassfee');
        var repairdepotfeeFiled = insurancerequestpanel.down('#repairdepotfee');
        var abatementfeeFiled = insurancerequestpanel.down('#abatementfee');

        var insurancefeeFiled = insurancerequestpanel.down('#insurancefee');

        insurancefeeFiled.setValue(cdwMoneyField.getValue() + tpliMoneyField.getValue() +
        dsiMoneyFiled.getValue() + psiMoneyFiled.getValue() +
        theftfeeFiled.getValue() + domesticglassfeeFiled.getValue() +
        importglassfee.getValue() + repairdepotfeeFiled.getValue() +
        abatementfeeFiled.getValue());
    },

    onPsiMoneyBlur: function (component, event, eOpts) {
        var insurancerequestpanel = component.up('#insurancerequestpanel');
        var cdwMoneyField = insurancerequestpanel.down('#cdwMoney');
        var tpliMoneyField = insurancerequestpanel.down('#tpliMoney');
        var dsiMoneyFiled = insurancerequestpanel.down('#dsiMoney');
        var psiMoneyFiled = insurancerequestpanel.down('#psiMoney');
        var theftfeeFiled = insurancerequestpanel.down('#theftfee');
        var domesticglassfeeFiled = insurancerequestpanel.down('#domesticglassfee');
        var importglassfee = insurancerequestpanel.down('#importglassfee');
        var repairdepotfeeFiled = insurancerequestpanel.down('#repairdepotfee');
        var abatementfeeFiled = insurancerequestpanel.down('#abatementfee');

        var insurancefeeFiled = insurancerequestpanel.down('#insurancefee');

        insurancefeeFiled.setValue(cdwMoneyField.getValue() + tpliMoneyField.getValue() +
        dsiMoneyFiled.getValue() + psiMoneyFiled.getValue() +
        theftfeeFiled.getValue() + domesticglassfeeFiled.getValue() +
        importglassfee.getValue() + repairdepotfeeFiled.getValue() +
        abatementfeeFiled.getValue());
    },

    onTheftfeeBlur: function (component, event, eOpts) {
        var insurancerequestpanel = component.up('#insurancerequestpanel');
        var cdwMoneyField = insurancerequestpanel.down('#cdwMoney');
        var tpliMoneyField = insurancerequestpanel.down('#tpliMoney');
        var dsiMoneyFiled = insurancerequestpanel.down('#dsiMoney');
        var psiMoneyFiled = insurancerequestpanel.down('#psiMoney');
        var theftfeeFiled = insurancerequestpanel.down('#theftfee');
        var domesticglassfeeFiled = insurancerequestpanel.down('#domesticglassfee');
        var importglassfee = insurancerequestpanel.down('#importglassfee');
        var repairdepotfeeFiled = insurancerequestpanel.down('#repairdepotfee');
        var abatementfeeFiled = insurancerequestpanel.down('#abatementfee');

        var insurancefeeFiled = insurancerequestpanel.down('#insurancefee');

        insurancefeeFiled.setValue(cdwMoneyField.getValue() + tpliMoneyField.getValue() +
        dsiMoneyFiled.getValue() + psiMoneyFiled.getValue() +
        theftfeeFiled.getValue() + domesticglassfeeFiled.getValue() +
        importglassfee.getValue() + repairdepotfeeFiled.getValue() +
        abatementfeeFiled.getValue());
    },

    onDomesticglassfeeBlur: function (component, event, eOpts) {
        var insurancerequestpanel = component.up('#insurancerequestpanel');
        var cdwMoneyField = insurancerequestpanel.down('#cdwMoney');
        var tpliMoneyField = insurancerequestpanel.down('#tpliMoney');
        var dsiMoneyFiled = insurancerequestpanel.down('#dsiMoney');
        var psiMoneyFiled = insurancerequestpanel.down('#psiMoney');
        var theftfeeFiled = insurancerequestpanel.down('#theftfee');
        var domesticglassfeeFiled = insurancerequestpanel.down('#domesticglassfee');
        var importglassfee = insurancerequestpanel.down('#importglassfee');
        var repairdepotfeeFiled = insurancerequestpanel.down('#repairdepotfee');
        var abatementfeeFiled = insurancerequestpanel.down('#abatementfee');

        var insurancefeeFiled = insurancerequestpanel.down('#insurancefee');

        insurancefeeFiled.setValue(cdwMoneyField.getValue() + tpliMoneyField.getValue() +
        dsiMoneyFiled.getValue() + psiMoneyFiled.getValue() +
        theftfeeFiled.getValue() + domesticglassfeeFiled.getValue() +
        importglassfee.getValue() + repairdepotfeeFiled.getValue() +
        abatementfeeFiled.getValue());
    },

    onImportglassfeeBlur: function (component, event, eOpts) {
        var insurancerequestpanel = component.up('#insurancerequestpanel');
        var cdwMoneyField = insurancerequestpanel.down('#cdwMoney');
        var tpliMoneyField = insurancerequestpanel.down('#tpliMoney');
        var dsiMoneyFiled = insurancerequestpanel.down('#dsiMoney');
        var psiMoneyFiled = insurancerequestpanel.down('#psiMoney');
        var theftfeeFiled = insurancerequestpanel.down('#theftfee');
        var domesticglassfeeFiled = insurancerequestpanel.down('#domesticglassfee');
        var importglassfee = insurancerequestpanel.down('#importglassfee');
        var repairdepotfeeFiled = insurancerequestpanel.down('#repairdepotfee');
        var abatementfeeFiled = insurancerequestpanel.down('#abatementfee');

        var insurancefeeFiled = insurancerequestpanel.down('#insurancefee');

        insurancefeeFiled.setValue(cdwMoneyField.getValue() + tpliMoneyField.getValue() +
        dsiMoneyFiled.getValue() + psiMoneyFiled.getValue() +
        theftfeeFiled.getValue() + domesticglassfeeFiled.getValue() +
        importglassfee.getValue() + repairdepotfeeFiled.getValue() +
        abatementfeeFiled.getValue());
    },

    onRepairdepotfeeBlur: function (component, event, eOpts) {
        var insurancerequestpanel = component.up('#insurancerequestpanel');
        var cdwMoneyField = insurancerequestpanel.down('#cdwMoney');
        var tpliMoneyField = insurancerequestpanel.down('#tpliMoney');
        var dsiMoneyFiled = insurancerequestpanel.down('#dsiMoney');
        var psiMoneyFiled = insurancerequestpanel.down('#psiMoney');
        var theftfeeFiled = insurancerequestpanel.down('#theftfee');
        var domesticglassfeeFiled = insurancerequestpanel.down('#domesticglassfee');
        var importglassfee = insurancerequestpanel.down('#importglassfee');
        var repairdepotfeeFiled = insurancerequestpanel.down('#repairdepotfee');
        var abatementfeeFiled = insurancerequestpanel.down('#abatementfee');

        var insurancefeeFiled = insurancerequestpanel.down('#insurancefee');

        insurancefeeFiled.setValue(cdwMoneyField.getValue() + tpliMoneyField.getValue() +
        dsiMoneyFiled.getValue() + psiMoneyFiled.getValue() +
        theftfeeFiled.getValue() + domesticglassfeeFiled.getValue() +
        importglassfee.getValue() + repairdepotfeeFiled.getValue() +
        abatementfeeFiled.getValue());
    },

    onAbatementfeeBlur: function (component, event, eOpts) {
        var insurancerequestpanel = component.up('#insurancerequestpanel');
        var cdwMoneyField = insurancerequestpanel.down('#cdwMoney');
        var tpliMoneyField = insurancerequestpanel.down('#tpliMoney');
        var dsiMoneyFiled = insurancerequestpanel.down('#dsiMoney');
        var psiMoneyFiled = insurancerequestpanel.down('#psiMoney');
        var theftfeeFiled = insurancerequestpanel.down('#theftfee');
        var domesticglassfeeFiled = insurancerequestpanel.down('#domesticglassfee');
        var importglassfee = insurancerequestpanel.down('#importglassfee');
        var repairdepotfeeFiled = insurancerequestpanel.down('#repairdepotfee');
        var abatementfeeFiled = insurancerequestpanel.down('#abatementfee');

        var insurancefeeFiled = insurancerequestpanel.down('#insurancefee');

        insurancefeeFiled.setValue(cdwMoneyField.getValue() + tpliMoneyField.getValue() +
        dsiMoneyFiled.getValue() + psiMoneyFiled.getValue() +
        theftfeeFiled.getValue() + domesticglassfeeFiled.getValue() +
        importglassfee.getValue() + repairdepotfeeFiled.getValue() +
        abatementfeeFiled.getValue());
    },

    onCompulsoryfeeBlur: function (component, event, eOpts) {
        var insurancerequestpanel = component.up('#insurancerequestpanel');
        var insurancefeeFiled = insurancerequestpanel.down('#insurancefee');
        var compulsoryfeeFiled = insurancerequestpanel.down('#compulsoryfee');
        var revenueFiled = insurancerequestpanel.down('#revenue');
        var totalfeeFiled = insurancerequestpanel.down('#totalfee');
        totalfeeFiled.setValue(insurancefeeFiled.getValue() + compulsoryfeeFiled.getValue() +
        revenueFiled.getValue());
    },

    onRevenueBlur: function (component, event, eOpts) {
        var insurancerequestpanel = component.up('#insurancerequestpanel');
        var insurancefeeFiled = insurancerequestpanel.down('#insurancefee');
        var compulsoryfeeFiled = insurancerequestpanel.down('#compulsoryfee');
        var revenueFiled = insurancerequestpanel.down('#revenue');
        var totalfeeFiled = insurancerequestpanel.down('#totalfee');
        totalfeeFiled.setValue(insurancefeeFiled.getValue() + compulsoryfeeFiled.getValue() +
        revenueFiled.getValue());
    },

    onInsuranceSaveButtonClick: function (button, e, eOpts) {
        /**基本信息*/
        var insurancerequestpanel = button.up('#insurancerequestpanel');
        var nameField = insurancerequestpanel.down('#name');
        var phoneField = insurancerequestpanel.down('#phone');
        var platNumField = insurancerequestpanel.down('#platNum');
        var firstRegisterDateField = insurancerequestpanel.down('#firstRegisterDate');
        var carTypeField = insurancerequestpanel.down('#carType');
        var frameNumberField = insurancerequestpanel.down('#frameNumber');
        var generationDateField = insurancerequestpanel.down('#generationDate');
        var engineNumberField = insurancerequestpanel.down('#engineNumber');
        var insuranceCompanyField = insurancerequestpanel.down('#insuranceCompany');
        var idCardField = insurancerequestpanel.down('#idCard');

        /**保险详细*/
        var cdwFiled = insurancerequestpanel.down('#cdwFiled');
        var cdwMoneyField = insurancerequestpanel.down('#cdwMoney');

        var tpliFiled = insurancerequestpanel.down('#tpliFiled');
        var tpliMoneyField = insurancerequestpanel.down('#tpliMoney');

        var dsiFiled = insurancerequestpanel.down('#dsiFiled');
        var dsiMoneyFiled = insurancerequestpanel.down('#dsiMoney');

        var psiFiled = insurancerequestpanel.down('#psiFiled');
        var psiMoneyFiled = insurancerequestpanel.down('#psiMoney');

        var theftinsureFiled = insurancerequestpanel.down('#theftinsureFiled');
        var theftfeeFiled = insurancerequestpanel.down('#theftfee');

        var domesticglassFiled = insurancerequestpanel.down('#domesticglassFiled');
        var domesticglassfeeFiled = insurancerequestpanel.down('#domesticglassfee');

        var importglassFiled = insurancerequestpanel.down('#importglassFiled');
        var importglassfee = insurancerequestpanel.down('#importglassfee');

        var repairdepotFiled = insurancerequestpanel.down('#repairdepotFiled');
        var repairdepotfeeFiled = insurancerequestpanel.down('#repairdepotfee');

        var abatementFiled = insurancerequestpanel.down('#abatementFiled');
        var abatementfeeFiled = insurancerequestpanel.down('#abatementfee');

        var insurancefeeFiled = insurancerequestpanel.down('#insurancefee');
        var compulsoryfeeFiled = insurancerequestpanel.down('#compulsoryfee');
        var revenueFiled = insurancerequestpanel.down('#revenue');

        var totalfeeFiled = insurancerequestpanel.down('#totalfee');
        var custnameFiled = insurancerequestpanel.down('#custname');
        var operatorFiled = insurancerequestpanel.down('#operator');


        if (!nameField.validate() || !phoneField.validate() || !platNumField.validate() || !engineNumberField.validate()) {
            Ext.Msg.alert('Status', '请正确填写信息.');
            return;
        }

        var url = Ext.getStore('ConfigStore').getAt(0).get('WebServerUrl');

        var generationDate = generationDateField.getValue();
        generationDate = (generationDate === null) ? 0 : generationDate.getTime() / 1000;

        var firstRegisterDate = firstRegisterDateField.getValue();
        firstRegisterDate = (firstRegisterDate === null) ? 0 : firstRegisterDate.getTime() / 1000;
        var data = {
            'f_name': nameField.getValue(),
            'f_phone': phoneField.getValue(),
            'f_platenum': platNumField.getValue(),
            'f_idcard': idCardField.getValue(),
            'f_engineno': engineNumberField.getValue(),
            'f_system': 100,
            'f_vehicletype': carTypeField.getValue(),
            'f_insurer': insuranceCompanyField.getValue(),
            'f_effecttime': generationDate,
            'f_vehicleregister': firstRegisterDate,
            'f_cdw': cdwFiled.getValue().cdw,
            'f_cdwfee': cdwMoneyField.getValue(),
            'f_tpli': tpliFiled.getValue().tpli,
            'f_tplifee': tpliMoneyField.getValue(),
            'f_dsi': dsiFiled.getValue().dsi,
            'f_dsifee': dsiMoneyFiled.getValue(),
            'f_psi': psiFiled.getValue().psi,
            'f_psifee': psiMoneyFiled.getValue(),
            'f_theftinsure': theftinsureFiled.getValue().theftinsure,
            'f_theftfee': theftfeeFiled.getValue(),
            'f_domesticglass': domesticglassFiled.getValue().domesticglass,
            'f_domesticglassfee': domesticglassfeeFiled.getValue(),
            'f_importglass': importglassFiled.getValue().importglass,
            'f_importglassfee': importglassfee.getValue(),
            'f_repairdepot': repairdepotFiled.getValue().repairdepot,
            'f_repairdepotfee': repairdepotfeeFiled.getValue(),
            'f_abatement': abatementFiled.getValue().abatement,
            'f_abatementfee': abatementfeeFiled.getValue(),
            'f_insurancefee': insurancefeeFiled.getValue(),
            'f_compulsoryfee': compulsoryfeeFiled.getValue(),
            'f_revenue': revenueFiled.getValue(),
            'f_totalfee': totalfeeFiled.getValue(),
            'f_custname': custnameFiled.getValue(),
            'f_operator': operatorFiled.getValue(),
            'f_sourcename': "",
        };

        Ext.Ajax.request({
            headers: {'Content-Type': 'application/json'},
            url: url + '/action/insurance/submit.do',
            params: JSON.stringify(data),
            success: function (response) {
                var text = response.responseText;
                var result = JSON.parse(text);

                if (result === null) {
                    Ext.Msg.alert('提示', '保存出错了，结果：' + text);
                    return;
                }

                if (result.succeed === true) {
                    Ext.Msg.alert('提示', '保存成功');
                } else {
                    Ext.Msg.alert('提示', '保存出错了，错误：' + result.ptError);
                    return;
                }

            }
        });
    }

});
