/*
 * File: app/view/RestPasswordPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.RestPasswordPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.restpasswordpanel',

    requires: [
        'CallCenterApp.view.RestPasswordPanelViewModel',
        'CallCenterApp.view.RestPasswordPanelViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'restpasswordpanel',
    viewModel: {
        type: 'restpasswordpanel'
    },
    height: 250,
    id: 'resetpwd',
    itemId: 'resetpwd',
    width: 400,
    closable: true,
    title: '密码重置',

    items: [
        {
            xtype: 'form',
            height: 219,
            id: 'resetpwdform',
            itemId: 'resetpwdform',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'phone',
                    itemId: 'phone',
                    maxWidth: 300,
                    width: 380,
                    fieldLabel: '手机号码',
                    maxLength: 150
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'verify',
                    maxWidth: 300,
                    fieldLabel: '验证码',
                    maxLength: 200
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'newpwd',
                    maxWidth: 300,
                    fieldLabel: '新密码',
                    maxLength: 200
                },
                {
                    xtype: 'button',
                    margin: '10 10 20 100',
                    width: 84,
                    text: '获取验证码',
                    listeners: {
                        click: 'onverifyButtonClick'
                    }
                },
                {
                    xtype: 'button',
                    margin: '10 10 20 2',
                    width: 58,
                    text: '提交',
                    listeners: {
                        click: 'onsubmitButtonClick'
                    }
                }
            ]
        }
    ]

});