/*
 * File: app/store/CityStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.store.CityStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'CityStore',
            autoLoad: false,
            proxy: {
                type: 'ajax',
                url: '/region/city.do',
                reader: {
                    type: 'json',
                    rootProperty: 'object.cityList'
                }
            },
            fields: [
                {
                    type: 'int',
                    mapping: 'cityID',
                    name: 'id'
                },
                {
                    type: 'string',
                    mapping: 'cityName',
                    name: 'text'
                }
            ]
        }, cfg)]);
    }
});