/*
 * File: app/view/MapPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('platformApp.view.MapPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.mapPanel',

    requires: [
        'Ext.Img'
    ],

    config: {
        id: 'mapPanel',
        itemId: 'mapPanel',
        items: [
            {
                xtype: 'image',
                height: 201,
                src: 'http://img3.imgtn.bdimg.com/it/u=1981510576,702115325&fm=21&gp=0.jpg'
            }
        ]
    }

});