/*
 * File: app/view/ActivityCarRequestPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.ActivityCarRequestPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.activitycarrequestpanel',

    requires: [
        'CallCenterApp.view.ActivityCarRequestPanelViewModel',
        'CallCenterApp.view.ActivityCarRequestPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Action',
        'Ext.grid.View'
    ],

    controller: 'activitycarrequestpanel',
    viewModel: {
        type: 'activitycarrequestpanel'
    },
    id: 'ActivityCarRequestPanel',
    itemId: 'ActivityCarRequestPanel',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    itemId: 'addBtn',
                    text: '添加',
                    listeners: {
                        click: 'onAddBtnClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'combobox',
            focusOnToFront: false,
            itemId: 'carBrand',
            margin: 10,
            width: 300,
            fieldLabel: '车辆品牌',
            labelAlign: 'right',
            labelWidth: 80,
            editable: false,
            emptyText: '请选择车辆品牌',
            displayField: 'name',
            store: 'CarBrandStord',
            valueField: 'id',
            listeners: {
                select: 'onCarBrandSelect'
            }
        },
        {
            xtype: 'combobox',
            frame: true,
            itemId: 'carset',
            margin: 10,
            width: 300,
            fieldLabel: '车系',
            labelAlign: 'right',
            labelWidth: 80,
            editable: false,
            emptyText: '请选择车辆车系',
            displayField: 'name',
            store: 'CarsetStore',
            valueField: 'id',
            listeners: {
                select: 'onCarsetSelect'
            }
        },
        {
            xtype: 'combobox',
            itemId: 'carType',
            margin: 10,
            width: 300,
            fieldLabel: '车辆型号',
            labelAlign: 'right',
            labelWidth: 80,
            editable: false,
            emptyText: '请选择车辆型号',
            displayField: 'name',
            store: 'CarTypeStore',
            valueField: 'id',
            listeners: {
                select: 'onCarTypeSelect'
            }
        },
        {
            xtype: 'combobox',
            frame: true,
            itemId: 'carColor',
            margin: 10,
            width: 300,
            fieldLabel: '颜色',
            labelAlign: 'right',
            labelWidth: 80,
            emptyText: '请填写车辆颜色',
            store: 'CarColorStore',
            valueField: 'value'
        },
        {
            xtype: 'textfield',
            itemId: 'lesspriceField',
            margin: 10,
            width: 300,
            fieldLabel: '优惠/降价',
            labelAlign: 'right',
            labelWidth: 80
        },
        {
            xtype: 'gridpanel',
            itemId: 'ActivityCarGridPanel',
            store: 'ActivityCarStore',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 50,
                    align: 'center',
                    text: '序号'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'carbrand',
                    text: '品牌'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'carset',
                    text: '车型'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'cartype',
                    text: '车款'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'color',
                    text: '车款颜色'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'lessprice',
                    text: '优惠/降价'
                },
                {
                    xtype: 'actioncolumn',
                    text: '操作',
                    altText: '操作',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                Ext.MessageBox.confirm('请确认', '您确认删除该条记录吗？',function(btn){

                                    if(btn==='no'){
                                        return;
                                    }else if(btn==='yes'){

                                        var id=record.data.svid;
                                        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

                                        Ext.Ajax.request({
                                            url:url+"/biz/app/salesvehicle/delete.do",
                                            params:{
                                                id:id
                                            },

                                            success:function(response){
                                                var text = response.responseText;
                                                var result = JSON.parse(text);

                                                if (result=== null) {
                                                    Ext.Msg.alert('提示', '删除出错了，结果：' + result);
                                                    return;
                                                }else if (result.succeed) {
                                                    view.store.reload();
                                                    Ext.Msg.alert('提示', '删除成功');
                                                }else {
                                                    Ext.Msg.alert('提示', '删除出错了，错误：' + result.ptError);
                                                    return;
                                                }
                                            },

                                            failure:function(){
                                                Ext.Msg.alert('提示','删除失败');

                                            },
                                        });

                                    }
                                });
                            },
                            altText: '删除',
                            iconCls: 'Bulletcross',
                            tooltip: '删除'
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        beforerender: 'onActivityRequestPanelBeforeRender'
    }

});