/*
 * File: app/view/ActivityRequestPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.ActivityRequestPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.activityrequestpanel',

    requires: [
        'CallCenterApp.view.ActivityRequestPanelViewModel',
        'CallCenterApp.view.ActivityRequestPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.form.field.TextArea'
    ],

    controller: 'activityrequestpanel',
    viewModel: {
        type: 'activityrequestpanel'
    },
    id: 'ActivityRequestPanel',
    itemId: 'ActivityRequestPanel',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    itemId: 'addBtn',
                    text: '添加',
                    listeners: {
                        click: 'onAddBtnClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'combobox',
            itemId: 'systemSelector',
            margin: 10,
            width: 300,
            fieldLabel: '系统',
            labelAlign: 'right',
            labelWidth: 80,
            editable: false,
            displayField: 'f_stname',
            store: 'BusinessSystemManagerStore',
            valueField: 'f_stid'
        },
        {
            xtype: 'combobox',
            itemId: 'typeSelector',
            margin: 10,
            width: 300,
            fieldLabel: '类型',
            labelAlign: 'right',
            labelWidth: 80,
            editable: false,
            displayField: 'name',
            store: 'ActivityTypeStore',
            valueField: 'id'
        },
        {
            xtype: 'textfield',
            itemId: 'titleField',
            margin: 10,
            width: 300,
            fieldLabel: '标题',
            labelAlign: 'right',
            labelWidth: 80
        },
        {
            xtype: 'container',
            height: 26,
            margin: 10,
            layout: 'column',
            items: [
                {
                    xtype: 'datefield',
                    itemId: 'startDate',
                    margin: '',
                    width: 300,
                    fieldLabel: '开始时间',
                    labelAlign: 'right',
                    labelWidth: 80,
                    format: 'Y-m-d'
                },
                {
                    xtype: 'timefield',
                    itemId: 'startTime',
                    renderData: 'new Data()',
                    width: 150,
                    format: 'H:i:s'
                }
            ]
        },
        {
            xtype: 'container',
            height: 26,
            margin: 10,
            layout: 'column',
            items: [
                {
                    xtype: 'datefield',
                    itemId: 'endDate',
                    margin: '',
                    width: 300,
                    fieldLabel: '结束时间',
                    labelAlign: 'right',
                    labelWidth: 80,
                    format: 'Y-m-d'
                },
                {
                    xtype: 'timefield',
                    itemId: 'endTime',
                    width: 150,
                    format: 'H:i:s'
                }
            ]
        },
        {
            xtype: 'textareafield',
            itemId: 'contentField',
            margin: 10,
            width: 450,
            fieldLabel: '内容',
            labelAlign: 'right',
            labelWidth: 80
        }
    ]

});