/*
 * File: app/view/BannerManagePanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.BannerManagePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.bannermanagepanel',

    requires: [
        'CallCenterApp.view.BannerManagePanelViewModel',
        'CallCenterApp.view.BannerManagePanelViewController',
        'Ext.grid.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Action',
        'Ext.grid.View',
        'Ext.Img',
        'Ext.ProgressBar',
        'Ext.form.field.File',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    controller: 'bannermanagepanel',
    viewModel: {
        type: 'bannermanagepanel'
    },
    id: 'BannerManagePanel',
    itemId: 'BannerManagePanel',
    layout: 'border',
    closable: true,
    title: 'Banner管理',

    items: [
        {
            xtype: 'panel',
            flex: 4,
            region: 'center',
            layout: 'fit',
            title: '',
            items: [
                {
                    xtype: 'gridpanel',
                    autoScroll: true,
                    itemId: 'BannerManageGridPanel',
                    title: '',
                    store: 'BannerManageStore',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            height: 38,
                            items: [
                                {
                                    xtype: 'combobox',
                                    itemId: 'systemSelector',
                                    width: 250,
                                    fieldLabel: '系统',
                                    labelAlign: 'right',
                                    labelWidth: 50,
                                    editable: false,
                                    displayField: 'f_stname',
                                    store: 'BusinessSystemManagerStore',
                                    valueField: 'f_stid',
                                    listeners: {
                                        select: 'onSystemSelectorSelect'
                                    }
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 50,
                            align: 'center',
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 160,
                            align: 'center',
                            dataIndex: 'desc',
                            text: '图片描述'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            align: 'center',
                            dataIndex: 'editorid',
                            text: '操作人'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 50,
                            align: 'center',
                            dataIndex: 'order',
                            text: '排序'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 160,
                            align: 'center',
                            dataIndex: 'image',
                            text: '图片地址'
                        },
                        {
                            xtype: 'actioncolumn',
                            text: '操作',
                            items: [
                                {
                                    handler: function (view, rowIndex, colIndex, item, e, record, row) {
                                        Ext.MessageBox.confirm('请确认', '您确认删除该条记录吗？', function (btn) {

                                            if (btn === 'no') {
                                                return;
                                            } else if (btn === 'yes') {

                                                var id = record.data.bnid;
                                                var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

                                                Ext.Ajax.request({
                                                    url: url + "/biz/app/banner/delete.do",
                                                    params: {
                                                        id: id
                                                    },

                                                    success: function (response) {
                                                        var text = response.responseText;
                                                        var result = JSON.parse(text);

                                                        if (result === null) {
                                                            Ext.Msg.alert('提示', '删除出错了，结果：' + result);
                                                            return;
                                                        } else if (result.succeed) {
                                                            view.store.reload();
                                                            Ext.Msg.alert('提示', '删除成功');
                                                        } else {
                                                            Ext.Msg.alert('提示', '删除出错了，错误：' + result.ptError);
                                                            return;
                                                        }
                                                    },

                                                    failure: function () {
                                                        Ext.Msg.alert('提示', '删除失败');

                                                    },
                                                });

                                            }
                                        });
                                    },
                                    altText: '删除',
                                    iconCls: 'Bulletcross',
                                    tooltip: '删除'
                                }
                            ]
                        }
                    ],
                    listeners: {
                        rowdblclick: 'onBannerManageGridPanelRowDblClick'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 3,
            region: 'east',
            split: true,
            autoScroll: true,
            itemId: 'imageShowPanel',
            width: 150,
            animCollapse: true,
            collapsible: true,
            title: '当前横幅图片',
            items: [
                {
                    xtype: 'image',
                    border: '5 5 5 5',
                    frame: true,
                    height: 325,
                    id: 'BannerImg',
                    itemId: 'BannerImg',
                    width: 510,
                    alt: '横幅图片',
                    title: '当前横幅图片'
                },
                {
                    xtype: 'panel',
                    height: 20,
                    itemId: 'ImageUpdatePanel',
                    title: '',
                    items: [
                        {
                            xtype: 'progressbar',
                            frame: true,
                            itemId: 'fileuploadProgressBar'
                        }
                    ]
                },
                {
                    xtype: 'filefield',
                    id: 'imageUploadFiled',
                    itemId: 'imageUploadFiled',
                    margin: 10,
                    width: 360,
                    fieldLabel: '图片',
                    labelAlign: 'right',
                    labelWidth: 60,
                    buttonMargin: 10,
                    buttonText: '打开...',
                    listeners: {
                        render: 'onImageFieldUploadFiledRender'
                    }
                },
                {
                    xtype: 'textfield',
                    itemId: 'orderField',
                    margin: 10,
                    width: 300,
                    fieldLabel: '排序',
                    labelAlign: 'right',
                    labelWidth: 60
                },
                {
                    xtype: 'textfield',
                    itemId: 'urlField',
                    margin: 10,
                    width: 300,
                    fieldLabel: '超链接',
                    labelAlign: 'right',
                    labelWidth: 60
                },
                {
                    xtype: 'combobox',
                    itemId: 'docSelector',
                    margin: 10,
                    width: 300,
                    fieldLabel: '文档',
                    labelAlign: 'right',
                    labelWidth: 60
                },
                {
                    xtype: 'textareafield',
                    height: 103,
                    itemId: 'descField',
                    margin: 10,
                    width: 300,
                    fieldLabel: '描述',
                    labelAlign: 'right',
                    labelWidth: 60
                },
                {
                    xtype: 'textfield',
                    hidden: true,
                    itemId: 'id',
                    margin: 10,
                    width: 300,
                    fieldLabel: '主键',
                    labelAlign: 'right',
                    labelWidth: 60
                },
                {
                    xtype: 'button',
                    itemId: 'addBtn',
                    margin: '10 0 0 50',
                    width: 53,
                    text: '添加',
                    listeners: {
                        click: 'onAddBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    disabled: true,
                    itemId: 'saveBtn',
                    margin: '10 0 0 50',
                    width: 53,
                    text: '保存',
                    listeners: {
                        click: 'onSaveBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'resetBtn',
                    margin: '10 0 0 50',
                    width: 53,
                    text: '重置'
                }
            ]
        }
    ],
    listeners: {
        beforerender: 'onBannerManagePanelBeforeRender'
    }

});