/*
 * File: app/view/BusinessSystemRequestPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.BusinessSystemRequestPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.businesssystemrequestpanel',

    requires: [
        'CallCenterApp.view.BusinessSystemRequestPanelViewModel',
        'CallCenterApp.view.BusinessSystemRequestPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.ComboBox'
    ],

    controller: 'businesssystemrequestpanel',
    viewModel: {
        type: 'businesssystemrequestpanel'
    },
    id: 'BusinessSystemRequestPanel',
    itemId: 'BusinessSystemRequestPanel',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    itemId: 'saveButton',
                    text: '保存',
                    listeners: {
                        click: 'onSaveButtonClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'resetButton',
                    text: '重置',
                    listeners: {
                        click: 'onResetButtonClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'textfield',
            itemId: 'systemIdField',
            margin: 15,
            fieldLabel: '系统编码',
            labelAlign: 'right',
            editable: false
        },
        {
            xtype: 'textfield',
            itemId: 'systemNameField',
            margin: 15,
            fieldLabel: '系统名称',
            labelAlign: 'right'
        },
        {
            xtype: 'combobox',
            itemId: 'fatherSystemField',
            margin: 15,
            fieldLabel: '父系统名称',
            labelAlign: 'right',
            editable: false,
            displayField: 'f_stname',
            store: 'BusinessSystemManagerStore',
            valueField: 'f_stid'
        },
        {
            xtype: 'textfield',
            itemId: 'authorizationSystemField',
            margin: 15,
            fieldLabel: '可授权系统',
            labelAlign: 'right'
        },
        {
            xtype: 'textfield',
            itemId: 'defaultUrlField',
            margin: 15,
            fieldLabel: '系统默认url',
            labelAlign: 'right'
        }
    ],
    listeners: {
        beforerender: 'onBusinessSystemRequestPanelBeforeRender'
    }

});