/*
 * File: app/view/ColumnRequestPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.ColumnRequestPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.columnrequestpanel',

    onSaveButtonClick: function (button, e, eOpts) {
        var columnRequestPanel = button.up('#ColumnRequestPanel');

        var itemId = columnManagePanel.down('#itemIdField');
        var name = columnManagePanel.down('#nameField');
        var pitemId = columnManagePanel.down('#pitemIdField');
        var desc = columnManagePanel.down('#descField');
        var status = columnManagePanel.down('#statusField');
        var order = columnManagePanel.down('#orderField');
        var stId = columnManagePanel.down('#stIdField');
        var ico = columnManagePanel.down('#icoField');
        var itemCode = columnManagePanel.down('#itemCodeField');


        if (name.getValue() === "" || stid.getValue() === "" || itemcode.getValue() === "") {
            Ext.Msg.alert('提示', '请填写必要信息!');
            return;
        }

        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

        Ext.Ajax.request({
            url: url + '',
            params: {
                'f_itemid': itemId.getValue(),
                'f_name': name.getValue(),
                'f_pitemid': pitemId.getValue(),
                'f_desc': desc.getValue(),
                'f_status': status.getValue(),
                'f_order': order.getValue(),
                'f_stid': stId.getValue(),
                'f_ico': ico.getValue(),
                'f_itemcode': itemCode.getValue()
            },
            success: function (response) {
                var text = response.responseText;
                var result = JSON.parse(text);
                if (result === null) {
                    Ext.Msg.alert('提示', '修改出错了，结果：' + text);
                    return;
                }

                if (result.succeed === true) {
                    Ext.getStore('ColumnManageStore').reload();
                    Ext.Msg.alert('提示', '修改成功');
                } else {
                    Ext.Msg.alert('提示', '修改出错了，错误：' + result.errMsg);
                }
            }
        });
    },

    onResetButtonC: function (button, e, eOpts) {
        this.onColumnRequestPanelBeforeRender();
    },

    onColumnRequestPanelBeforeRender: function (component, eOpts) {
        var columnRequestPanel = Ext.getCmp('ColumnRequestPanel');

        columnRequestPanel.down('#itemIdField').setValue(columnRequestPanel.date.f_itemid);
        columnRequestPanel.down('#nameField').setValue(columnRequestPanel.date.f_name);
        columnRequestPanel.down('#pitemIdField').setValue(columnRequestPanel.date.f_pitemid);
        columnRequestPanel.down('#descField').setValue(columnRequestPanel.date.f_desc);
        columnRequestPanel.down('#statusField').setValue(columnRequestPanel.date.f_status);
        columnRequestPanel.down('#orderField').setValue(columnRequestPanel.date.f_order);
        columnRequestPanel.down('#stIdField').setValue(columnRequestPanel.date.f_stid);
        columnRequestPanel.down('#icoField').setValue(columnRequestPanel.date.f_ico);
        columnRequestPanel.down('#itemCodeField').setValue(columnRequestPanel.date.f_itemcode);
    }

});
