/*
 * File: app/view/ColumnManagePanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.ColumnManagePanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.columnmanagepanel',

    onAddButtonClick: function (button, e, eOpts) {
        var columnManagePanel = button.up('#ColumnManagePanel');

        var name = columnManagePanel.down('#nameField');
        var pitemId = columnManagePanel.down('#pitemIdField');
        var desc = columnManagePanel.down('#descField');
        var status = columnManagePanel.down('#statusField');
        var order = columnManagePanel.down('#orderField');
        var stId = columnManagePanel.down('#stIdField');
        var ico = columnManagePanel.down('#icoField');
        var itemCode = columnManagePanel.down('#itemCodeField');


        if (name.getValue() === "" || stid.getValue() === "" || itemcode.getValue() === "") {
            Ext.Msg.alert('提示', '请填写必要信息!');
            return;
        }

        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

        Ext.Ajax.request({
            url: url + '',
            params: {
                'f_name': name.getValue(),
                'f_pitemid': pitemId.getValue(),
                'f_desc': desc.getValue(),
                'f_status': status.getValue(),
                'f_order': order.getValue(),
                'f_stid': stId.getValue(),
                'f_ico': ico.getValue(),
                'f_itemcode': itemCode.getValue()
            },
            success: function (response) {
                var text = response.responseText;
                var result = JSON.parse(text);
                if (result === null) {
                    Ext.Msg.alert('提示', '添加出错了，结果：' + text);
                    return;
                }

                if (result.succeed === true) {
                    Ext.getStore('columnManageStore').reload();
                    Ext.Msg.alert('提示', '添加成功');
                } else {
                    Ext.Msg.alert('提示', '添加出错了，错误：' + result.errMsg);
                }
            }
        });
    },

    onResetButtonClick: function (button, e, eOpts) {
        var columnManagePanel = button.up('#ColumnManagePanel');

        columnManagePanel.down('#nameField').setValue("");
        columnManagePanel.down('#pitemIdField').setValue(-1);
        columnManagePanel.down('#descField').setValue("");
        columnManagePanel.down('#statusField').setValue("");
        columnManagePanel.down('#orderField').setValue("");
        columnManagePanel.down('#stIdField').setValue("");
        columnManagePanel.down('#icoField').setValue("");
        columnManagePanel.down('#itemCodeField').setValue("");
    },

    onColumnManageGridPanelRowDblClick: function (tableview, record, tr, rowIndex, e, eOpts) {
        var columnManagePanel = Ext.getCmp('ColumnManagePanel');
        var columnManageGridPanel = columnManagePanel.down('#ColumnManageGridPanel');

        if (columnManageGridPanel.selection === null) {
            return;
        }

        var columnRequestPanel = new CallCenterApp.view.ColumnRequestPanel({
            date: columnManageGridPanel.selection.data

        });

        var myForm = new Ext.window.Window({
            modal: true,
            autoScroll: true,
            title: '栏目修改',
            width: 365,
            height: 420
        });

        myForm.add(columnManageGridPanel);
        myForm.show();
    },

    onColumnManagePanelRender: function (component, eOpts) {
        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

        var ColumnManageStore = Ext.getStore('ColumnManageStore');

        var ajaxProxy = ColumnManageStore.getProxy();

        ajaxProxy.setUrl(url + "");

        ColumnManageStore.load();
    }

});
