/*
 * File: app/view/EtcRequestPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.EtcRequestPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.etcrtpanel',

    requires: [
        'CallCenterApp.view.EtcRequestPanelViewModel',
        'CallCenterApp.view.EtcRequestPanelViewController',
        'Ext.form.field.Text',
        'Ext.container.Container',
        'Ext.button.Button'
    ],

    controller: 'etcrequestpanel',
    viewModel: {
        type: 'etcrequestpanel'
    },
    itemId: 'etcRequestPanel',
    bodyPadding: 10,
    closable: true,
    title: 'ETC开卡申请',

    items: [
        {
            xtype: 'textfield',
            itemId: 'nameField',
            margin: 10,
            width: 380,
            fieldLabel: '姓名',
            labelWidth: 60,
            allowBlank: false,
            emptyText: '必需填写'
        },
        {
            xtype: 'textfield',
            itemId: 'phoneField',
            margin: 10,
            width: 380,
            fieldLabel: '电话',
            labelWidth: 60,
            allowBlank: false,
            emptyText: '必需填写',
            regex: /^1(3|5|8)[0-9]{9}$/,
            regexText: '手机号码为11位'
        },
        {
            xtype: 'textfield',
            itemId: 'descField',
            margin: 10,
            width: 380,
            fieldLabel: '备注',
            labelWidth: 60
        },
        {
            xtype: 'container',
            layout: 'absolute',
            items: [
                {
                    xtype: 'button',
                    x: 260,
                    y: 10,
                    height: 35,
                    itemId: 'submitBtn',
                    width: 100,
                    text: '提交资料',
                    listeners: {
                        click: 'onSubmitBtnClick'
                    }
                }
            ]
        }
    ]

});