/*
 * File: app/view/EticketConsumePanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.EticketConsumePanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.eticketconsumepanel',

    onEticketShopInfoSelect: function (combo, records, eOpts) {
        var shopId = records[0].data.shopId;
        var EticketConsumerStore = Ext.getStore('EticketConsumerStore');
        var ajaxProxy = EticketConsumerStore.getProxy();
        var url = Ext.getStore('ConfigStore').getAt(0).get('WebServerUrl');
        ajaxProxy.setUrl(url + "/action/cons/list.do?f_useshop=" + shopId);
        EticketConsumerStore.load();
    },

    onEticketConsumerGridpanelRowDblClick: function (tableview, record, tr, rowIndex, e, eOpts) {
        var EticketConsumePanel = tableview.up('#EticketConsumePanel');

        var EticketShopInfo = EticketConsumePanel.down('#EticketShopInfo');

        var shopId = EticketShopInfo.getValue();

        var id = record.data.f_id;

        var EticketInitDetailStore = Ext.getStore('EticketInitDetailStore');
        var ajaxProxy = EticketInitDetailStore.getProxy();
        var url = Ext.getStore('ConfigStore').getAt(0).get('WebServerUrl');

        ajaxProxy.setUrl(url + "/action/eticket/detail.do?shopId=" + shopId + "&ticketid=" + id);

        EticketInitDetailStore.load();

    }

});
