/*
 * File: app/view/InsStatusPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.InsStatusPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.insstpanel',

    requires: [
        'CallCenterApp.view.InsStatusPanelViewModel',
        'CallCenterApp.view.InsStatusPanelViewController',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.Number',
        'Ext.form.field.Number',
        'Ext.view.Table',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.property.Grid',
        'Ext.button.Button',
        'Ext.toolbar.Paging'
    ],

    controller: 'insstatuspanel',
    viewModel: {
        type: 'insstatuspanel'
    },
    id: 'insStatusPanel',
    itemId: 'insStatusPanel',
    layout: 'fit',
    bodyPadding: 10,
    closable: true,
    title: '保险申请查询',

    items: [
        {
            xtype: 'container',
            layout: 'border',
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 12,
                    region: 'center',
                    autoScroll: true,
                    itemId: 'InsStatusGridpanel',
                    title: '',
                    columnLines: true,
                    store: 'InsStatusStore',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 50,
                            align: 'left',
                            dataIndex: 'index',
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'f_name',
                            lockable: false,
                            text: '姓名'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'f_platenum',
                            locked: true,
                            text: '车牌号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 142,
                            align: 'center',
                            dataIndex: 'f_phone',
                            text: '电话'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            align: 'center',
                            dataIndex: 'f_idcard',
                            text: '身份证'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 180,
                            align: 'center',
                            dataIndex: 'f_appletime',
                            text: '申请时间',
                            format: 'Y-m-d H:i:s'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function (value, metaData, record, rowIndex, colIndex, store, view) {
                                if (value === 0) {
                                    return "待处理";
                                } else if (value === 1) {
                                    return "处理中";
                                } else if (value === 2) {
                                    return "已接受";
                                } else if (value === 3) {
                                    return "被驳回";
                                } else if (value === 4) {
                                    return "已出单";
                                } else if (value === 5) {
                                    return "已送单";
                                } else if (value === 6) {
                                    return "业务完成";
                                } else if (value === 7) {
                                    return "完成咨询";
                                }
                            },
                            align: 'center',
                            dataIndex: 'f_status',
                            text: '状态',
                            editor: {
                                xtype: 'combobox',
                                autoRender: true,
                                autoShow: true,
                                itemId: 'statusCombobox',
                                hideLabel: true,
                                editable: false,
                                selectOnFocus: true,
                                displayField: 'name',
                                queryMode: 'local',
                                store: 'StatusStore',
                                typeAhead: true,
                                valueField: 'id'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            align: 'center',
                            dataIndex: 'f_source',
                            text: '来源'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 117,
                            align: 'center',
                            dataIndex: 'f_insurancefee',
                            text: '商业险金额(元)',
                            editor: {
                                xtype: 'numberfield',
                                itemId: 'insurancefeeEditer',
                                regex: /^\d{0,8}\.{0,1}(\d{1,2})$/,
                                regexText: '输入合法信息',
                                minValue: 0,
                                step: 0.1
                            }
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'f_compulsoryfee',
                            text: '交强险费用(元)',
                            editor: {
                                xtype: 'numberfield',
                                itemId: 'compulsoryfeeEditer',
                                regex: /^\d{0,8}\.{0,1}(\d{1,2})$/,
                                regexText: '请输入合法信息'
                            }
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'f_revenue',
                            text: '车船税费用(元)',
                            editor: {
                                xtype: 'numberfield',
                                itemId: 'revenueEditer',
                                regex: /^\d{0,8}\.{0,1}(\d{1,2})$/,
                                regexText: '请输入合法信息'
                            }
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'f_totalfee',
                            text: '保险金额(元)',
                            editor: {
                                xtype: 'numberfield',
                                disabled: true,
                                itemId: 'insTotalfeeEditer',
                                editable: false,
                                regex: /^\d{0,8}\.{0,1}(\d{1,2})$/,
                                regexText: '请输入合法信息',
                                minValue: 0
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'f_insurer',
                            text: '保险公司'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'f_desc',
                            text: '备注',
                            editor: {
                                xtype: 'textfield',
                                itemId: 'descTextFieldEditor'
                            }
                        }
                    ],
                    viewConfig: {
                        xtype: 'tableview',
                        frame: true,
                        enableTextSelection: true
                    },
                    plugins: [
                        {
                            ptype: 'cellediting',
                            clicksToEdit: 1
                        }
                    ],
                    listeners: {
                        cellcontextmenu: 'onInsStatusGridpanelCellContextMenu',
                        selectionchange: 'onInsStatusGridpanelSelectionChange'
                    }
                },
                {
                    xtype: 'propertygrid',
                    flex: 3,
                    region: 'east',
                    split: true,
                    frame: true,
                    id: 'InsStatusPropertyGridPanel',
                    itemId: 'InsStatusPropertyGridPanel',
                    width: 150,
                    collapsible: true,
                    title: '属性',
                    titleCollapse: true,
                    sortableColumns: false
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    itemId: 'refreshBtn',
                    iconCls: 'Arrowrefresh',
                    text: '刷新',
                    listeners: {
                        click: 'onRefreshBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'exportBtn',
                    iconCls: 'Applicationosxgo',
                    text: '导出内容',
                    listeners: {
                        click: 'onExportBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'saveBtn',
                    iconCls: 'Pagesave',
                    text: '修改保存',
                    listeners: {
                        click: 'onSaveBtnClick'
                    }
                }
            ]
        },
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            draggable: true,
            width: 360,
            displayInfo: true,
            store: 'InsStatusStore'
        }
    ],
    listeners: {
        render: 'onInsStatusPanelRender'
    }

});