/*
 * File: app/view/LoginWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.LoginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginwindow',

    requires: [
        'CallCenterApp.view.LoginWindowViewModel',
        'CallCenterApp.view.LoginWindowViewController',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'loginwindow',
    viewModel: {
        type: 'loginwindow'
    },
    autoShow: true,
    height: 267,
    itemId: 'loginWindow',
    width: 400,
    bodyBorder: true,
    bodyStyle: 'background-image:url(\'resources/image/login-background.jpg\');padding:55px 5px 0',
    closable: false,
    title: '客户关系管理系统',

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'textfield',
            itemId: 'userField',
            margin: 10,
            fieldLabel: '用户名',
            labelWidth: 80,
            selectOnFocus: true,
            listeners: {
                blur: 'onUserFieldBlur',
                render: 'onUserFieldRender'
            }
        },
        {
            xtype: 'textfield',
            itemId: 'pwdField',
            margin: 10,
            fieldLabel: '密码',
            labelWidth: 80,
            inputType: 'password'
        },
        {
            xtype: 'button',
            height: 30,
            itemId: 'loginBtn',
            margin: 10,
            width: 80,
            text: '登录',
            listeners: {
                click: 'onLoginBtnClick'
            }
        }
    ],
    listeners: {
        render: 'onLoginWindowRender'
    }

});