/*
 * File: app/view/MessageTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.MessageTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.messagetabpanel',

    requires: [
        'CallCenterApp.view.MessageTabPanelViewModel',
        'CallCenterApp.view.MessageTabPanelViewController',
        'Ext.tab.Tab',
        'Ext.form.field.TextArea',
        'Ext.form.Panel',
        'Ext.form.field.File'
    ],

    controller: 'messagetabpanel',
    viewModel: {
        type: 'messagetabpanel'
    },
    height: 381,
    itemId: 'messageTabPanel',
    width: 597,
    closable: true,
    title: '短信发送',
    activeTab: 0,

    items: [
        {
            xtype: 'panel',
            id: 'postSingleMessagePanel',
            itemId: 'postSingleMessagePanel',
            title: '短信单发',
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'messagePhone',
                    fieldLabel: '手机号码',
                    allowBlank: false,
                    blankText: '手机号码不能为空',
                    emptyText: '请输入手机号码',
                    regex: /^1(3|5|8)[0-9]{9}$/,
                    regexText: '手机号码为11位'
                },
                {
                    xtype: 'textareafield',
                    height: 155,
                    itemId: 'messageContent',
                    width: 494,
                    fieldLabel: '短信内容',
                    emptyText: '短信内容超过70字符将按多条收费'
                },
                {
                    xtype: 'button',
                    itemId: 'postMessageButton',
                    margin: '10 20 50 100',
                    text: '提交发送',
                    listeners: {
                        click: 'onPostMessageButtonClick'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            id: 'postMultipleMessagePanel',
            itemId: 'postMultipleMessagePanel',
            title: '短信群发',
            items: [
                {
                    xtype: 'form',
                    id: 'multipleMessageContainer',
                    itemId: 'multipleMessageContainer',
                    items: [
                        {
                            xtype: 'filefield',
                            frame: true,
                            id: 'inputExcelField',
                            itemId: 'inputExcelField',
                            width: 368,
                            fieldLabel: '导入Excel文件',
                            listeners: {
                                render: 'onInputExcelFieldRender'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});