/*
 * File: app/view/SqdStatusPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.SqdStatusPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sqdstpanel',

    requires: [
        'CallCenterApp.view.SqdStatusPanelViewModel',
        'CallCenterApp.view.SqdStatusPanelViewController',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.form.field.ComboBox',
        'Ext.view.Table',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.property.Grid',
        'Ext.button.Button',
        'Ext.toolbar.Paging'
    ],

    controller: 'sqdstatuspanel',
    viewModel: {
        type: 'sqdstatuspanel'
    },
    itemId: 'sqdStatusPanel',
    layout: 'fit',
    bodyPadding: 10,
    closable: true,
    title: '社区店预约查询',

    items: [
        {
            xtype: 'container',
            itemId: 'SqdStatusPanelContainer',
            layout: 'border',
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 12,
                    region: 'center',
                    autoScroll: true,
                    id: 'SqdStatusGridPanel',
                    itemId: 'SqdStatusGridPanel',
                    title: '',
                    store: 'SqdStatusStore',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 50,
                            dataIndex: 'index',
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: '姓名'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'phone',
                            text: '电话'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'platenum',
                            text: '车牌号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 180,
                            dataIndex: 'subtime',
                            text: '提交时间'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 180,
                            dataIndex: 'ordertime',
                            text: '预约时间',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function (value, metaData, record, rowIndex, colIndex, store, view) {
                                if (value === 0) {
                                    return "待处理";
                                } else if (value === 1) {
                                    return "处理中";
                                } else if (value === 2) {
                                    return "已接受";
                                } else if (value === 3) {
                                    return "被驳回";
                                } else if (value === 4) {
                                    return "已出单";
                                } else if (value === 5) {
                                    return "已送单";
                                } else if (value === 6) {
                                    return "业务完成";
                                } else if (value === 7) {
                                    return "完成咨询";
                                }
                            },
                            dataIndex: 'f_status',
                            text: '状态',
                            editor: {
                                xtype: 'combobox',
                                itemId: 'sqdStatusComboBox',
                                readOnly: false,
                                editable: false,
                                selectOnFocus: true,
                                displayField: 'name',
                                store: 'StatusStore',
                                valueField: 'id'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'source',
                            text: '来源'
                        }
                    ],
                    viewConfig: {
                        xtype: 'tableview'
                    },
                    plugins: [
                        {
                            ptype: 'cellediting',
                            clicksToEdit: 1
                        }
                    ],
                    listeners: {
                        select: 'onSqdStatusGridPanelSelect'
                    }
                },
                {
                    xtype: 'propertygrid',
                    flex: 5,
                    region: 'east',
                    split: true,
                    frame: true,
                    id: 'SqdStatusPropertyPanel',
                    itemId: 'SqdStatusPropertyPanel',
                    width: 150,
                    animCollapse: true,
                    collapsible: true,
                    title: '属性',
                    titleCollapse: true,
                    sortableColumns: false
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    itemId: 'refreshBtn',
                    text: '刷新',
                    listeners: {
                        click: 'onRefreshBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'copyBtn',
                    text: '复制',
                    listeners: {
                        click: 'onCopyBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'saveBtn',
                    text: '保存',
                    listeners: {
                        click: 'onSaveBtnClick'
                    }
                }
            ]
        },
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'SqdStatusStore'
        }
    ],
    listeners: {
        render: 'onSqdStatusPanelRender'
    }

});