/*
 * File: app/view/SqdStatusPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.SqdStatusPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.sqdstatuspanel',

    onSqdStatusGridPanelSelect: function (rowmodel, record, index, eOpts) {
        var record = record.data;

        var SqdStatusPropertyPanel = Ext.getCmp('SqdStatusPropertyPanel');

        SqdStatusPropertyPanel.setSource({
            f_name: record.f_name,

            f_phone: record.f_phone,

            f_platenum: record.f_platenum,

            f_idcard: record.f_idcard,

            f_engineno: record.f_engineno,

            appletime: record.appletime,

            bespeakdate: record.bespeakdate,

            f_bespeaktime: record.f_bespeaktime,

            f_brand_model: record.f_brand_model,

            f_mileage: (record.f_mileage === undefined) ? undefined : record.f_mileage + '公里',

            f_repairproject: record.f_repairproject,

            f_shopaddress: record.f_shopaddress,

            f_shopcode: record.f_shopcode,

            f_source: record.f_source,

            f_sourcename: record.f_sourcename,

            status: record.status,

            f_desc: record.f_desc
        }, {
            f_name: {
                displayName: '姓名',
            },
            f_phone: {
                displayName: '手机号码',
            },
            f_platenum: {
                displayName: '车牌号码',
            },
            f_idcard: {
                displayName: '身份证号码',
            },
            f_engineno: {
                displayName: '发动机号码',
            },
            appletime: {
                displayName: '提交时间',
            },
            bespeakdate: {
                displayName: '预约日期',
            },
            f_bespeaktime: {
                displayName: '预约时间',
            },
            f_brand_model: {
                displayName: '车辆型号',
            },
            f_mileage: {
                displayName: '行驶里程',
            },
            f_repairproject: {
                displayName: '维修项目',
            },
            f_shopaddress: {
                displayName: '店铺地址',
            },
            f_shopcode: {
                displayName: '店铺编号',
            },
            f_source: {
                displayName: '来源信息',
            },
            f_sourcename: {
                displayName: '来源名称',
            },
            status: {
                displayName: '状态',
            },
            f_desc: {
                displayName: '备注',
            },


        });

    },

    onRefreshBtnClick: function (button, e, eOpts) {
        var sqdStatusStore = Ext.getStore('SqdStatusStore');
        var ajaxProxy = sqdStatusStore.getProxy();
        var url = Ext.getStore('ConfigStore').getAt(0).get('WebServerUrl');
        ajaxProxy.setUrl(url + "/action/sqd/list.do?system=ytadmin@7788");
        sqdStatusStore.load();
    },

    onCopyBtnClick: function (button, e, eOpts) {

    },

    onSaveBtnClick: function (button, e, eOpts) {
        var sqdStatusPanel = button.up('#sqdStatusPanel');
        var url = Ext.getStore('ConfigStore').getAt(0).get('WebServerUrl');
        var SqdStatusStore = Ext.getStore('SqdStatusStore');
        var records = SqdStatusStore.getModifiedRecords().slice(0);
        if (records.length < 1) {
            return;
        }
        Ext.MessageBox.confirm('请确认', '您确认修改吗？', function (btn) {
            if (btn === 'no') {
                return;
            } else if (btn === 'yes') {

                var jsonArray = [];
                Ext.each(records, function (item) {
                    var f_bsid = item.data.f_bsid;
                    var f_status = item.data.f_status;
                    jsonArray.push({f_bsid: f_bsid, f_status: f_status});
                });
                Ext.Ajax.request({

                    url: url + "/action/sqd/update.do",
                    params: {
                        status: JSON.stringify(jsonArray),
                    },

                    success: function (response) {
                        var text = response.responseText;
                        var result = JSON.parse(text);

                        if (result === null) {
                            Ext.Msg.alert('提示', '保存出错了，结果：' + result);
                            return;
                        }

                        if (result[0].succeed) {

                            alert('保存成功');
                            var SqdStatusStore = Ext.getStore('SqdStatusStore');
                            var ajaxProxy = SqdStatusStore.getProxy();
                            var url = Ext.getStore('ConfigStore').getAt(0).get('WebServerUrl');
                            ajaxProxy.setUrl(url + "/action/sqd/list.do?system=ytadmin@7788");
                            SqdStatusStore.load();

                        } else {
                            Ext.Msg.alert('提示', '保存出错了，错误：' + result.ptError);
                            return;
                        }
                    },

                    failure: function () {
                        Ext.Msg.alert('提示', '失败');
                    },
                });

            }
        });

    },

    onSqdStatusPanelRender: function (component, eOpts) {
        this.onRefreshBtnClick(null, null, null);
    }

});
