/*
 * File: app/view/systemOprateAdmin.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.systemOprateAdmin', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.systemoprateadmin',

    requires: [
        'CallCenterApp.view.systemOprateAdminViewModel',
        'CallCenterApp.view.systemOprateAdminViewController',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    controller: 'systemoprateadmin',
    viewModel: {
        type: 'systemoprateadmin'
    },
    id: 'systemOprateAdmin',
    itemId: 'systemOprateAdmin',
    iconCls: 'Groupkey',
    title: '系统操作',

    items: [
        {
            xtype: 'menu',
            floating: false,
            itemId: 'systemOprateMenu',
            minWidth: 250,
            width: 120,
            title: '',
            items: [
                {
                    xtype: 'menuitem',
                    id: 'authorityManager',
                    itemId: 'authorityManager',
                    iconCls: 'Lock',
                    text: '权限管理'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'businessSystemManager',
                    text: '业务系统管理'
                }
            ],
            listeners: {
                click: 'onSystemOprateMenuClick'
            }
        }
    ]

});