/*
 * File: app/model/adviceModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.model.adviceModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Date',
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            name: 'f_name'
        },
        {
            name: 'f_phone'
        },
        {
            name: 'f_content'
        },
        {
            type: 'date',
            name: 'f_createtime',
            dateFormat: 'timestamp'
        },
        {
            type: 'boolean',
            name: 'f_read'
        },
        {
            name: 'f_mid'
        }
    ]
});