/*
 * File: app/model/PtCustomerInfo.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.model.PtCustomerInfo', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Date'
    ],

    fields: [
        {
            name: 'f_name'
        },
        {
            name: 'f_sex'
        },
        {
            name: 'f_phone'
        },
        {
            name: 'f_idcard'
        },
        {
            name: 'f_address'
        },
        {
            name: 'f_ciid'
        },
        {
            type: 'date',
            name: 'f_initdate',
            dateFormat: 'timestamp'
        }
    ]
});