/*
 * File: app/model/SqdCallbackModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.model.SqdCallbackModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer'
    ],

    fields: [
        {
            type: 'int',
            name: 'f_iid'
        },
        {
            mapping: 'mebInfo[0].f_mname',
            name: 'f_name'
        },
        {
            mapping: 'mebInfo[0].f_phone',
            name: 'f_phone'
        },
        {
            mapping: 'mebInfo[0].f_carno',
            name: 'f_carno'
        },
        {
            mapping: 'mebInfo[0].f_cartype',
            name: 'f_cartype'
        },
        {
            mapping: 'callInfo.f_initdate',
            name: 'f_initdate'
        },
        {
            mapping: 'callInfo.f_endtime',
            name: 'f_endtime'
        },
        {
            mapping: 'callInfo.f_closetime',
            name: 'f_closetime'
        },
        {
            mapping: 'callInfo.f_status',
            name: 'f_status'
        },
        {
            mapping: 'callInfo.f_total',
            name: 'f_total'
        },
        {
            mapping: 'callInfo.f_rebate',
            name: 'f_rebate'
        },
        {
            mapping: 'callInfo.f_amount',
            name: 'f_amount'
        },
        {
            mapping: 'callInfo.f_description',
            name: 'f_description'
        },
        {
            mapping: 'callInfo.deptname',
            name: 'f_deptname'
        },
        {
            mapping: 'callInfo.f_oddetail',
            name: 'f_oddetail'
        },
        {
            mapping: 'callInfo.f_infotime',
            name: 'f_infotime'
        }
    ]
});