/*
 * File: app/model/HgStatusModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.model.HgStatusModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer'
    ],

    fields: [
        {
            type: 'string',
            mapping: 'f_name',
            name: 'name'
        },
        {
            type: 'string',
            mapping: 'f_phone',
            name: 'phone'
        },
        {
            type: 'string',
            mapping: 'f_ciid',
            name: 'f_ciid'
        },
        {
            type: 'string',
            name: 'index'
        },
        {
            type: 'int',
            name: 'f_status'
        },
        {
            type: 'string',
            mapping: 'f_source',
            name: 'source'
        },
        {
            type: 'string',
            name: 'appletime'
        },
        {
            name: 'f_price'
        },
        {
            type: 'string',
            name: 'f_desc'
        }
    ]
});