/*
 * File: app/model/InsStatusModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.model.InsStatusModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],

    fields: [
        {
            type: 'int',
            mapping: 'f_isid',
            name: 'f_isid'
        },
        {
            mapping: 'f_name',
            name: 'f_name'
        },
        {
            mapping: 'f_phone',
            name: 'f_phone'
        },
        {
            mapping: 'f_idcard',
            name: 'f_idcard'
        },
        {
            mapping: 'f_platenum',
            name: 'f_platenum'
        },
        {
            type: 'date',
            mapping: 'f_appletime',
            name: 'f_appletime',
            dateReadFormat: 'timestamp',
            dateWriteFormat: 'ms'
        },
        {
            name: 'f_status'
        },
        {
            mapping: 'f_source',
            name: 'f_source'
        },
        {
            mapping: 'f_busitype',
            name: 'f_biztype'
        },
        {
            mapping: 'f_insurer',
            name: 'f_insurer'
        },
        {
            mapping: 'f_safepackage',
            name: 'f_safepackage'
        },
        {
            mapping: 'f_totalfee',
            name: 'f_totalfee'
        },
        {
            name: 'f_desc'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'f_insurancefee'
        },
        {
            name: 'f_compulsoryfee'
        },
        {
            name: 'f_revenue'
        }
    ]
});