package com.order.data.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TaskDetail implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task_detail.id
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task_detail.task_id
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task_detail.user_id
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    private Long userId;

    private String userName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task_detail.price
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    private BigDecimal price;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task_detail.create_time
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task_detail.remark
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    private String remark;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_detail.id
     *
     * @return the value of tb_task_detail.id
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_detail.id
     *
     * @param id the value for tb_task_detail.id
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_detail.task_id
     *
     * @return the value of tb_task_detail.task_id
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_detail.task_id
     *
     * @param taskId the value for tb_task_detail.task_id
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_detail.user_id
     *
     * @return the value of tb_task_detail.user_id
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_detail.user_id
     *
     * @param userId the value for tb_task_detail.user_id
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_detail.price
     *
     * @return the value of tb_task_detail.price
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_detail.price
     *
     * @param price the value for tb_task_detail.price
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_detail.create_time
     *
     * @return the value of tb_task_detail.create_time
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_detail.create_time
     *
     * @param createTime the value for tb_task_detail.create_time
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_detail.remark
     *
     * @return the value of tb_task_detail.remark
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_detail.remark
     *
     * @param remark the value for tb_task_detail.remark
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}