/*
 * File: app/view/BizStatusPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.BizStatusPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.bizstatuspanel',

    requires: [
        'CallCenterApp.view.BizStatusPanelViewModel',
        'CallCenterApp.view.BizStatusPanelViewController',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.grid.column.RowNumberer',
        'Ext.view.Table',
        'Ext.grid.property.Grid'
    ],

    controller: 'bizstatuspanel',
    viewModel: {
        type: 'bizstatuspanel'
    },
    itemId: 'bizStatusPanel',
    bodyPadding: 10,
    closable: true,
    title: '客户业务查询',

    items: [
        {
            xtype: 'container',
            itemId: 'BizStatusConditionContainer',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'phoneField',
                    width: 233,
                    fieldLabel: '查询条件',
                    labelWidth: 60,
                    emptyText: '输入手机号码',
                    listeners: {
                        keypress: 'onPhoneFieldKeypress'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'findBtn',
                    width: 62,
                    text: '查询',
                    listeners: {
                        click: 'onFindBtnClick'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            height: 540,
            id: 'BizStatusGridContainer',
            layout: 'border',
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 12,
                    region: 'center',
                    autoScroll: true,
                    itemId: 'StatusGridPanel',
                    collapsible: false,
                    title: '',
                    store: 'BizStatusStore',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 69,
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 108,
                            dataIndex: 'name',
                            text: '姓名'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'phone',
                            text: '电话'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'status',
                            text: '状态'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'appletime',
                            text: '提交时间'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'type',
                            text: '业务类型'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'source',
                            text: '来源'
                        }
                    ],
                    viewConfig: {
                        xtype: 'tableview'
                    },
                    listeners: {
                        rowdblclick: 'onStatusGridPanelRowDblClick',
                        select: 'onStatusGridPanelSelect'
                    }
                },
                {
                    xtype: 'propertygrid',
                    flex: 5,
                    region: 'east',
                    split: true,
                    id: 'BizStatusPropertyPanel',
                    itemId: 'BizStatusPropertyPanel',
                    width: 150,
                    collapsible: true,
                    title: '属性',
                    titleCollapse: true,
                    sourceConfig: {
                        name: {
                            displayName: 'nameFiled',
                            
                        }
                    }
                }
            ]
        }
    ]

});