/*
 * File: app/view/BusinessSystemManagerPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.BusinessSystemManagerPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.businesssystemmanagerpanel',

    onAddButtonClick: function (button, e, eOpts) {
        var businessSystemManagerPanel = button.up('#BusinessSystemManagerPanel');

        var systemName = businessSystemManagerPanel.down('#systemNameField');
        var fatherSystem = businessSystemManagerPanel.down('#fatherSystemField');
        var authorizationSystem = businessSystemManagerPanel.down('#authorizationSystemField');
        var defaultUrl = businessSystemManagerPanel.down('#defaultUrlField');


        if (systemName.getValue() === "") {
            Ext.Msg.alert('提示', '请填写必要信息!');
            return;
        }

        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

        Ext.Ajax.request({
            url: url + '/biz/app/add.do',
            params: {
                'f_stname': systemName.getValue(),
                'f_pstid': fatherSystem.getValue(),
                'f_accredit': authorizationSystem.getValue(),
                'f_url': defaultUrl.getValue()
            },
            success: function (response) {
                var text = response.responseText;
                var result = JSON.parse(text);
                if (result === null) {
                    Ext.Msg.alert('提示', '添加出错了，结果：' + text);
                    return;
                }

                if (result.succeed === true) {
                    Ext.getStore('BusinessSystemManagerStore').reload();
                    Ext.Msg.alert('提示', '添加成功');
                } else {
                    Ext.Msg.alert('提示', '添加出错了，错误：' + result.errMsg);
                }
            }
        });
    },

    onBusinessSystemManagerGridPanelRowDblClick: function (tableview, record, tr, rowIndex, e, eOpts) {
        var businessSystemManagerPanel = Ext.getCmp('BusinessSystemManagerPanel');
        var businessSystemManagerGridPanel = businessSystemManagerPanel.down('#BusinessSystemManagerGridPanel');

        if (businessSystemManagerGridPanel.selection === null) {
            return;
        }

        var businessSystemRequestPanel = new CallCenterApp.view.BusinessSystemRequestPanel({
            date: businessSystemManagerGridPanel.selection.data

        });

        var myForm = new Ext.window.Window({
            modal: true,
            autoScroll: true,
            title: '业务系统修改',
            width: 348,
            height: 321
        });

        myForm.add(businessSystemRequestPanel);
        myForm.show();
    },

    onBusinessSystemManagerPanelBeforeRender: function (component, eOpts) {
        var url = Ext.getStore('ConfigStore').getAt(0).get('OrderUrl');

        var businessSystemManagerStore = Ext.getStore('BusinessSystemManagerStore');

        var ajaxProxy = businessSystemManagerStore.getProxy();

        ajaxProxy.setUrl(url + "/biz/app/list.do");

        businessSystemManagerStore.load();
    }

});
