/*
 * File: app/view/CarsetImagAddPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.CarsetImagAddPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.carsetimagaddpanel',

    requires: [
        'CallCenterApp.view.CarsetImagAddPanelViewModel',
        'CallCenterApp.view.CarsetImagAddPanelViewController',
        'Ext.grid.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.View',
        'Ext.Img',
        'Ext.ProgressBar',
        'Ext.form.field.File',
        'Ext.button.Button'
    ],

    controller: 'carsetimagaddpanel',
    viewModel: {
        type: 'carsetimagaddpanel'
    },
    height: 522,
    id: 'carsetImagAddpanel',
    itemId: 'carsetImagAddpanel',
    width: 680,
    layout: 'border',
    closable: true,
    title: '车系图片添加',
    titleCollapse: false,

    items: [
        {
            xtype: 'gridpanel',
            flex: 4,
            region: 'center',
            autoScroll: true,
            itemId: 'carsetImagAddGridPanel',
            title: '',
            store: 'NewCarsetStore',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'combobox',
                            itemId: 'carbrandSelect',
                            fieldLabel: '车辆品牌',
                            displayField: 'name',
                            store: 'CarBrandStord',
                            valueField: 'id',
                            listeners: {
                                select: 'onCarbrandSelectSelect'
                            }
                        },
                        {
                            xtype: 'combobox',
                            itemId: 'carfirmsSelect',
                            fieldLabel: '车辆厂商',
                            displayField: 'title',
                            store: 'CarMenuStore',
                            valueField: 'id',
                            listeners: {
                                select: 'onCarfirmsSelectSelect'
                            }
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 68,
                    align: 'center',
                    text: '序号'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'id',
                    text: '车系ID'
                },
                {
                    xtype: 'gridcolumn',
                    width: 159,
                    align: 'center',
                    dataIndex: 'fullName',
                    text: '车系名称'
                },
                {
                    xtype: 'gridcolumn',
                    width: 162,
                    align: 'center',
                    dataIndex: 'carlevel',
                    text: '车系等级'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    align: 'center',
                    dataIndex: 'minguide',
                    text: '最低配价格(万)'
                },
                {
                    xtype: 'gridcolumn',
                    width: 167,
                    align: 'center',
                    dataIndex: 'maxguide',
                    text: '最高配价格(万)'
                }
            ],
            listeners: {
                render: 'onCarsetImagAddGridPanelRender',
                selectionchange: 'onCarsetImagAddGridPanelSelectionChange'
            }
        },
        {
            xtype: 'panel',
            flex: 3,
            region: 'east',
            split: true,
            autoScroll: true,
            id: 'imageShowPanel',
            itemId: 'imageShowPanel',
            width: 150,
            animCollapse: true,
            collapsible: true,
            title: '车系当前图片',
            items: [
                {
                    xtype: 'image',
                    border: '5 5 5 5',
                    frame: true,
                    height: 400,
                    id: 'carsetImagContent',
                    itemId: 'carsetImagContent',
                    width: 510,
                    alt: '车系图片',
                    title: '车系当前图片'
                },
                {
                    xtype: 'panel',
                    height: 60,
                    id: 'ImageUpdatePanel',
                    itemId: 'ImageUpdatePanel',
                    title: '',
                    items: [
                        {
                            xtype: 'progressbar',
                            frame: true,
                            id: 'fileuploadProgressBar',
                            itemId: 'fileuploadProgressBar'
                        },
                        {
                            xtype: 'container',
                            width: 562,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'filefield',
                                    id: 'imageFiled',
                                    itemId: 'imageFiled',
                                    width: 277,
                                    fieldLabel: '更新图片',
                                    labelWidth: 60,
                                    buttonText: '打开...',
                                    listeners: {
                                        render: 'onImageUploadFiledRender'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'updateSaveBtn',
                                    margin: '0 0 0 20',
                                    width: 53,
                                    text: '提交',
                                    listeners: {
                                        click: 'onUpdateSaveBtnClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});