/*
 * File: app/view/CustomerStatusPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.CustomerStatusPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ctstatuspanel',

    requires: [
        'CallCenterApp.view.CustomerStatusPanelViewModel',
        'CallCenterApp.view.CustomerStatusPanelViewController',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.grid.property.Grid'
    ],

    controller: 'customerstatuspanel',
    viewModel: {
        type: 'customerstatuspanel'
    },
    itemId: 'customerStatusPanel',
    bodyPadding: 10,
    closable: true,
    title: '客户数据查询',

    items: [
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'phoneField',
                    width: 300,
                    fieldLabel: '电话',
                    labelWidth: 60,
                    emptyText: ''
                },
                {
                    xtype: 'button',
                    itemId: 'findBtn',
                    text: '查询',
                    listeners: {
                        click: 'onFindBtnClick'
                    }
                }
            ]
        },
        {
            xtype: 'propertygrid',
            itemId: 'basicPropGrid',
            collapsed: false,
            collapsible: true,
            title: '基本资料'
        },
        {
            xtype: 'propertygrid',
            itemId: 'hgPropGrid',
            collapsed: false,
            collapsible: true,
            title: '弘高资料'
        },
        {
            xtype: 'propertygrid',
            itemId: 'etcPropGrid',
            collapsible: true,
            title: 'ETC资料'
        },
        {
            xtype: 'propertygrid',
            itemId: 'insPropGrid',
            collapsible: true,
            title: '保险资料'
        }
    ]

});