/*
 * File: app/view/EditProfilePanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.EditProfilePanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.editprofilepanel',

    requires: [
        'CallCenterApp.view.EditProfilePanelViewModel',
        'CallCenterApp.view.EditProfilePanelViewController',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'editprofilepanel',
    viewModel: {
        type: 'editprofilepanel'
    },
    frame: true,
    height: 237,
    id: 'editprofilePanel',
    itemId: 'editprofilePanel',
    margin: '',
    width: 363,
    bodyBorder: true,
    closable: true,
    title: '资料修改',
    titleCollapse: false,
    jsonSubmit: false,

    items: [
        {
            xtype: 'textfield',
            itemId: 'name',
            fieldLabel: '姓  名'
        },
        {
            xtype: 'textfield',
            itemId: 'idcard',
            fieldLabel: '身份证'
        },
        {
            xtype: 'button',
            itemId: 'submitbtn',
            margin: '20 10 50 100',
            width: 53,
            text: '提交',
            listeners: {
                click: 'onSubmitbtnClick'
            }
        },
        {
            xtype: 'button',
            itemId: 'resetbtn',
            margin: '10 10 50 10',
            width: 57,
            text: '重置',
            listeners: {
                click: 'onResetbtnClick'
            }
        }
    ]

});