/*
 * File: app/view/EtcRequestPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.EtcRequestPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.etcrequestpanel',

    onSubmitBtnClick: function (button, e, eOpts) {
        var etcRequestPanel = button.up('#etcRequestPanel');
        var nameField = etcRequestPanel.down('#nameField');
        var phoneField = etcRequestPanel.down('#phoneField');
        var descField = etcRequestPanel.down('#descField');

        if (!nameField.validate() || !phoneField.validate()) {
            Ext.Msg.alert('Status', '请正确填写信息.');
            return;
        }


        var url = Ext.getStore('ConfigStore').getAt(0).get('WebServerUrl');
        var data = {
            'f_name': nameField.getValue(),
            'f_phone': phoneField.getValue(),
            'f_desc': descField.getValue(),
            'f_system': 100,
        };

        Ext.Ajax.request({
            headers: {'Content-Type': 'application/json'},
            url: url + '/action/etcNew/submit.do',
            params: JSON.stringify(data),

            success: function (response) {
                //var text=Ext.util.JSON.decode(response.responseText);
                var text = response.responseText;
                var result = JSON.parse(text);


                if (result === null) {
                    Ext.Msg.alert('提示', '保存出错了，结果：' + result);
                    return;
                }

                if (result.succeed === true) {
                    Ext.Msg.alert('提示', '保存成功');
                } else {
                    Ext.Msg.alert('提示', '保存出错了，错误：' + result.ptError);
                    return;
                }

                nameField.reset();
                phoneField.reset();
                descField.reset();
            }
        });
    }

});
