/*
 * File: app/view/EtcRecordPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.EtcRecordPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.etcrecordpanel',

    onEtcRecordBtnClick: function (button, e, eOpts) {
        var etcRecordPanel = Ext.getCmp('etcRecordPanel');
        var plateNumField = etcRecordPanel.down('#plateNumField');
        var beginDateField = etcRecordPanel.down('#beginDateField');
        var endDateField = etcRecordPanel.down('#endDateField');

        var recordStore = Ext.getStore('EtcRecordStore');
        var ajaxProxy = recordStore.getProxy();
        ajaxProxy.setExtraParam('platenum', plateNumField.getValue());
        ajaxProxy.setExtraParam('begindate', beginDateField.getValue());
        ajaxProxy.setExtraParam('enddate', endDateField.getValue());
        var url = Ext.getStore('ConfigStore').getAt(0).get('WebServerUrl');
        ajaxProxy.setUrl(url + "/action/etc/record.do");

        recordStore.load();
        etcRecordPanel.down('#etcRecordGrid').updateLayout();
    },

    onEtcRecordPanelDestroy: function (component, eOpts) {
        var recordStore = Ext.getStore('EtcRecordStore');
        recordStore.removeAll();
    }

});
