/*
 * File: app/view/eticketBusiness.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.eticketBusiness', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.eticketbusiness',

    requires: [
        'CallCenterApp.view.eticketBusinessViewModel',
        'CallCenterApp.view.eticketBusinessViewController',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    controller: 'eticketbusiness',
    viewModel: {
        type: 'eticketbusiness'
    },
    itemId: 'eticketBusiness',
    title: '优惠券业务',

    items: [
        {
            xtype: 'menu',
            floating: false,
            itemId: 'menueticket',
            minWidth: 300,
            width: 733,
            title: '',
            items: [
                {
                    xtype: 'menuitem',
                    itemId: 'eticketRequestItem',
                    width: 300,
                    text: '电子券制作'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'eticketGiveItem',
                    plain: false,
                    text: '电子券赠送'
                },
                {
                    xtype: 'menuitem',
                    id: 'eticketRuleGiveItem',
                    itemId: 'eticketRuleGiveItem',
                    text: '赠送规则'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'eticketManageItem',
                    text: '电子券管理'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'eticketConsumeItem',
                    text: '消费记录管理'
                },
                {
                    xtype: 'menuitem',
                    id: 'eticketGiveMagItem',
                    itemId: 'eticketGiveMagItem',
                    text: '赠送记录管理'
                }
            ],
            listeners: {
                click: 'onMenuEticketClick'
            }
        }
    ]

});