/*
 * File: app/view/eticketRequestPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.eticketRequestPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.eticketrequestpanel',

    requires: [
        'CallCenterApp.view.eticketRequestPanelViewModel',
        'CallCenterApp.view.eticketRequestPanelViewController',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.form.field.TextArea',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.Time',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.button.Button'
    ],

    controller: 'eticketrequestpanel',
    viewModel: {
        type: 'eticketrequestpanel'
    },
    autoScroll: true,
    height: 969,
    id: 'eticketRequestPanel',
    itemId: 'eticketRequestPanel',
    margin: 10,
    width: 741,
    bodyBorder: true,
    closable: true,
    title: '优惠券信息',

    items: [
        {
            xtype: 'textfield',
            itemId: 'eticketName',
            fieldLabel: '标题',
            name: 'eticketName',
            allowBlank: false
        },
        {
            xtype: 'textfield',
            itemId: 'systemName',
            fieldLabel: '系统名称'
        },
        {
            xtype: 'numberfield',
            itemId: 'eticketCount',
            fieldLabel: '数量',
            name: 'eticketCount',
            allowBlank: false,
            minValue: 0
        },
        {
            xtype: 'combobox',
            itemId: 'eticketType',
            fieldLabel: '类型',
            name: 'eticketType',
            allowBlank: false,
            editable: false,
            displayField: 'name',
            queryMode: 'local',
            store: 'EticketTypeStore',
            valueField: 'id',
            listeners: {
                select: 'onEticketTypeSelect'
            }
        },
        {
            xtype: 'numberfield',
            hidden: true,
            itemId: 'eticketRebate',
            fieldLabel: '折扣',
            name: 'eticketRebate',
            allowBlank: false,
            maxText: '最大值为1',
            maxValue: 1,
            minText: '最小值为0',
            minValue: 0,
            step: 0.01
        },
        {
            xtype: 'numberfield',
            hidden: true,
            itemId: 'eticketMoney',
            fieldLabel: '金额(元)',
            name: 'eticketMoney',
            allowBlank: false,
            minValue: 0
        },
        {
            xtype: 'datefield',
            itemId: 'eticketStartDate',
            fieldLabel: '有效开始日期',
            name: 'eticketStartDate',
            submitValue: false,
            allowBlank: false
        },
        {
            xtype: 'datefield',
            itemId: 'eticketEndDate',
            fieldLabel: '有效截止日期',
            name: 'eticketEndDate',
            submitValue: false,
            allowBlank: false
        },
        {
            xtype: 'numberfield',
            hidden: true,
            itemId: 'eticketOneGet',
            fieldLabel: '单人单日限领',
            name: 'eticketOneGet',
            value: 0,
            minValue: 0
        },
        {
            xtype: 'numberfield',
            hidden: true,
            itemId: 'eticketOneUse',
            fieldLabel: '单人单日限用',
            name: 'eticketOneUse',
            value: 0,
            minValue: 0
        },
        {
            xtype: 'numberfield',
            hidden: true,
            itemId: 'eticketGetLimit',
            fieldLabel: '单人限领',
            name: 'eticketGetLimit',
            value: 0,
            minValue: 0
        },
        {
            xtype: 'numberfield',
            hidden: true,
            itemId: 'eticketMinSpend',
            fieldLabel: '最低消费额(元)',
            name: 'eticketMinSpend',
            value: 0,
            minValue: 0
        },
        {
            xtype: 'textareafield',
            height: 50,
            itemId: 'eticketDetails',
            width: 552,
            fieldLabel: '优惠详情',
            labelAlign: 'top',
            name: 'eticketDetails',
            emptyText: '请输入优惠详情',
            preventScrollbars: true
        },
        {
            xtype: 'textareafield',
            height: 62,
            itemId: 'eticketMsgcontent',
            width: 554,
            fieldLabel: '短信内容',
            labelAlign: 'top',
            name: 'eticketMsgcontent',
            emptyText: '短信内容'
        },
        {
            xtype: 'textareafield',
            height: 62,
            itemId: 'eticketRemind',
            width: 554,
            fieldLabel: '提醒内容',
            labelAlign: 'top',
            name: 'eticketMind',
            emptyText: '提醒内容'
        },
        {
            xtype: 'textfield',
            hidden: true,
            itemId: 'eticketImage',
            fieldLabel: '形象图片',
            name: 'eticketImage'
        },
        {
            xtype: 'container',
            autoScroll: true,
            height: 29,
            itemId: 'limitRadioContainer',
            width: 362,
            items: [
                {
                    xtype: 'radiogroup',
                    itemId: 'limitRadioGroup',
                    width: 228,
                    fieldLabel: '',
                    items: [
                        {
                            xtype: 'radiofield',
                            itemId: 'limitRadio',
                            name: 'limitRadio',
                            boxLabel: '限制',
                            inputValue: '0'
                        },
                        {
                            xtype: 'radiofield',
                            name: 'limitRadio',
                            boxLabel: '不限制',
                            checked: true,
                            inputValue: '1'
                        }
                    ],
                    listeners: {
                        change: 'onLimitRadioGroupChange'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            frame: true,
            height: 433,
            hidden: true,
            id: 'limitContainer',
            itemId: 'limitContainer',
            width: 569,
            items: [
                {
                    xtype: 'timefield',
                    itemId: 'starttime',
                    fieldLabel: '使用开始时间段',
                    name: 'starttime',
                    format: 'H:i:s'
                },
                {
                    xtype: 'timefield',
                    itemId: 'endtime',
                    fieldLabel: '使用截止时间段',
                    name: 'endtime',
                    format: 'H:i:s'
                },
                {
                    xtype: 'textareafield',
                    height: 72,
                    itemId: 'userule',
                    width: 530,
                    fieldLabel: '使用规则',
                    name: 'userule',
                    validateOnChange: false,
                    validateOnBlur: false,
                    emptyText: '使用规则',
                    grow: true
                },
                {
                    xtype: 'container',
                    autoScroll: true,
                    height: 258,
                    layout: 'border',
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 5,
                            region: 'center',
                            autoScroll: true,
                            id: 'limitUseShopGridPanel',
                            itemId: 'limitUseShopGridPanel',
                            title: '限制使用店铺',
                            autoLoad: true,
                            store: 'limitUseShopStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'shopName',
                                    text: '店铺名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'shopId',
                                    text: '店铺编号'
                                }
                            ],
                            selModel: {
                                selType: 'checkboxmodel',
                                allowDeselect: true,
                                mode: 'SIMPLE',
                                showHeaderCheckbox: true
                            },
                            listeners: {
                                select: 'onLimitUseShopGridPanelSelect',
                                deselect: 'onLimitUseShopGridPanelDeselect'
                            }
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'east',
                            id: 'LimitUseServerGrid',
                            itemId: 'LimitUseServerGrid',
                            width: 237,
                            title: '店铺使用服务',
                            store: 'limitUseServerStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'fnameanddes',
                                    text: '服务名称'
                                }
                            ],
                            selModel: {
                                selType: 'checkboxmodel',
                                allowDeselect: true,
                                mode: 'SIMPLE',
                                showHeaderCheckbox: true
                            },
                            listeners: {
                                select: 'onLimitUseServerGridSelect',
                                deselect: 'onLimitUseServerGridDeselect'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            height: 30,
            itemId: 'submitEticketBtn',
            width: 104,
            text: '提交',
            listeners: {
                click: 'onSubmitEticketBtnClick'
            }
        }
    ]

});