/*
 * File: app/view/eticketRequestPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.eticketRequestPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.eticketrequestpanel',

    onEticketTypeSelect: function (combo, records, eOpts) {
        var eticketRequestPanel = combo.up('#eticketRequestPanel');
        var rebateField = eticketRequestPanel.down('#eticketRebate');
        var MoneyField = eticketRequestPanel.down('#eticketMoney');

        var id = records[0].data.id;

        if (id === '代金券') {
            rebateField.hide();
            MoneyField.show();
        } else if (id === '折扣券') {
            rebateField.show();
            MoneyField.hide();
        } else if (id === '普通券') {
            rebateField.hide();
            MoneyField.hide();
        }
    },

    onLimitRadioGroupChange: function (field, newValue, oldValue, eOpts) {
        var eticketRequestPanel = field.up('#eticketRequestPanel');
        var starttime = eticketRequestPanel.down('#starttime');
        var endtime = eticketRequestPanel.down('#endtime');
        var userule = eticketRequestPanel.down('#userule');
        var limitShop = eticketRequestPanel.down('#limitShop');
        var limitContainer = Ext.getCmp('limitContainer');


        if (newValue.limitRadio === '0') {
            limitContainer.show();
            //             starttime.show();
            //             endtime.show();
            //             userule.show();
            //             limitShop.show();
        } else if (newValue.limitRadio === '1') {
            limitContainer.hide();
            //            starttime.hide();
            //             endtime.hide();
            //             userule.hide();
            //             limitShop.hide();
        }
        var limitRadioContainer = eticketRequestPanel.down('#limitRadioContainer');
        limitRadioContainer.updateLayout();
    },

    onLimitUseShopGridPanelSelect: function (rowmodel, record, index, eOpts) {
        var record = record.data;
        var requestPanel = Ext.getCmp('eticketRequestPanel');
        requestPanel.arr.push({shopId: record.shopId, content: []});

        var limitUseServerStore = Ext.getStore('limitUseServerStore');

        // Success
        var successCallback = function (resp, ops) {
            var result = Ext.JSON.decode(resp.responseText);
            limitUseServerStore.removeAll();
            limitUseServerStore.add(result.ROOT);
        };
        // Failure
        var failureCallback = function (resp, ops) {

            Ext.Msg.alert('Failure', resp);

        };
        Ext.Ajax.request({
            url: 'http://58.20.41.200:8099/g4studio/ServiceAction',
            /***'http://sqd.hg-rzzl.com/g4studio/ServiceAction',**/
            params: {
                f_deptid: record.deptid,
            },
            success: successCallback,
            failure: failureCallback
        });

    },

    onLimitUseShopGridPanelDeselect: function (rowmodel, record, index, eOpts) {
        var requestPanel = Ext.getCmp('eticketRequestPanel');
        for (var i = 0; i < requestPanel.arr.length; i++) {
            var item = requestPanel.arr[i];
            var b = item.shopId === record.data.shopId;
            if (item.shopId === record.data.shopId) {

                Ext.Array.remove(requestPanel.arr, item);
            }
        }

    },

    onLimitUseServerGridSelect: function (rowmodel, record, index, eOpts) {
        var limitUseShopGrid = Ext.getCmp('limitUseShopGridPanel');
        var durrent = limitUseShopGrid.getSelectionModel().selected.items;
        var durrentRecord = durrent[durrent.length - 1];
        /**当前店铺对象**/

        var requestPanel = Ext.getCmp('eticketRequestPanel');
        for (var i = 0; i < requestPanel.arr.length; i++) {
            var item = requestPanel.arr[i];

            if (item.shopId === durrentRecord.data.shopId) {
                item.content.push({f_gsid: record.data.f_gsid, f_sid: record.data.f_sid});
            }
        }


    },

    onLimitUseServerGridDeselect: function (rowmodel, record, index, eOpts) {
        var limitUseShopGrid = Ext.getCmp('limitUseShopGridPanel');
        var durrent = limitUseShopGrid.getSelectionModel().selected.items;
        var durrentRecord = durrent[durrent.length - 1];
        /**当前店铺选中项**/

        var requestPanel = Ext.getCmp('eticketRequestPanel');
        for (var i = 0; i < requestPanel.arr.length; i++) {
            var item = requestPanel.arr[i];

            if (item.shopId === durrentRecord.data.shopId) {

                for (var i = 0; i < item.content.length; i++) {
                    var contentItem = item.content[i];
                    if (contentItem.f_gsid === record.data.f_gsid) {

                        Ext.Array.remove(item.content, contentItem);
                    }
                }
            }
        }

    },

    onSubmitEticketBtnClick: function (button, e, eOpts) {

        /**获取页面元素值*/
        var eticketRequestPanel = button.up('#eticketRequestPanel');


        /**获取限制店铺信息*/
        var limitGrigPanel = eticketRequestPanel.down('#limitUseShopGridPanel');
        //var records=limitGrigPanel.getSelectionModel().selected.items;
        var jsonArray = eticketRequestPanel.arr;
        // if(jsonArray.length>0){
        //     Ext.each(records,function(item){
        //         var shopId=item.data.shopId;
        //         var shopName=item.data.shopName;
        //         jsonArray.push({shopId:shopId,shopName:shopName});
        //     });

        // }

        var jsonArrayStr = (jsonArray.length > 0) ? JSON.stringify(jsonArray) : null;


        var nameField = eticketRequestPanel.down('#eticketName');
        var systemName = eticketRequestPanel.down('#systemName');
        var countField = eticketRequestPanel.down('#eticketCount');
        var typeField = eticketRequestPanel.down('#eticketType');

        var rebateField = eticketRequestPanel.down('#eticketRebate');
        var MoneyField = eticketRequestPanel.down('#eticketMoney');
        var startDateField = eticketRequestPanel.down('#eticketStartDate');
        var endDateField = eticketRequestPanel.down('#eticketEndDate');

        var oneGetField = eticketRequestPanel.down('#eticketOneGet');
        var oneUseField = eticketRequestPanel.down('#eticketOneUse');
        var getLimitField = eticketRequestPanel.down('#eticketGetLimit');

        var minSpendField = eticketRequestPanel.down('#eticketMinSpend');
        var detailsField = eticketRequestPanel.down('#eticketDetails');
        var msgcontentField = eticketRequestPanel.down('#eticketMsgcontent');
        var remaindField = eticketRequestPanel.down('#eticketRemind');
        var imageField = eticketRequestPanel.down('#eticketImage');
        var startTimeField = eticketRequestPanel.down('#starttime');
        var endTimeField = eticketRequestPanel.down('#endtime');
        var useruleField = eticketRequestPanel.down('#userule');
        var limitShopField = eticketRequestPanel.down('#limitShop');

        var starttime = startDateField.getValue();
        var endtime = endDateField.getValue();
        starttime = (starttime === null) ? 0 : starttime.getTime() / 1000;
        endtime = (endtime === null) ? 0 : endtime.getTime() / 1000;

        var startLimit = (startTimeField.rawValue === "") ? null : startTimeField.rawValue;
        var endLimit = (endTimeField.rawValue === "") ? null : endTimeField.rawValue;

        if (systemName.getValue() === null || nameField.getValue() === null || countField.getValue() === null || typeField.getValue() === null) {
            Ext.Msg.alert('提示', '请填写必要信息!');
            return;
        }


        var data = {
            'f_name': nameField.getValue(),
            'f_type': typeField.getValue(),
            'f_starttime': starttime,
            'f_endtime': endtime,
            'f_oneuse': oneUseField.getValue(),
            'f_oneget': oneGetField.getValue(),
            'f_getlimite': getLimitField.getValue(),
            'f_minspending': minSpendField.getValue(),
            'f_money': MoneyField.getValue(),
            'f_rebate': rebateField.getValue(),
            'f_prenum': countField.getValue(),
            'f_details': detailsField.getValue(),
            'f_message': msgcontentField.getValue(),
            'f_image': imageField.getValue(),
            'f_remindmessage': remaindField.getValue(),
            'f_usetime': startLimit + ";" + endLimit,
            'f_userule': useruleField.getValue(),
            'f_useshop': jsonArrayStr,
            'f_initnum': countField.getValue(),
            'f_sysmid': systemName.getValue()

        };
        var url = Ext.getStore('ConfigStore').getAt(0).get('WebServerUrl');

        Ext.Ajax.request({
            headers: {'Content-Type': 'application/json'},
            url: url + '/action/eticket/submit.do',
            params: JSON.stringify(data),
            success: function (response) {
                var text = response.responseText;
                var result = JSON.parse(text);

                if (result === null) {
                    Ext.Msg.alert('提示', '保存出错了，结果：' + text);
                    return;
                }

                if (result.succeed === true) {
                    Ext.Msg.alert('提示', '保存成功');
                } else {
                    Ext.Msg.alert('提示', '保存出错了，错误：' + result.errMsg);
                }
            }
        });
    }

});
