/*
 * File: app/view/hgBusiness.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.hgBusiness', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.hgbusiness',

    requires: [
        'CallCenterApp.view.hgBusinessViewModel',
        'CallCenterApp.view.hgBusinessViewController',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    controller: 'hgbusiness',
    viewModel: {
        type: 'hgbusiness'
    },
    itemId: 'hgBusiness',
    title: '弘高业务',

    items: [
        {
            xtype: 'menu',
            floating: false,
            hidden: false,
            itemId: 'menuHg',
            items: [
                {
                    xtype: 'menuitem',
                    itemId: 'hgRequestItem',
                    text: '融资申请'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'hgStatusItem',
                    text: '融资状态查询'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'hgQuestionsItem',
                    text: '问题咨询管理'
                }
            ],
            listeners: {
                click: 'onMenuHgClick'
            }
        }
    ]

});