/*
 * File: app/view/HgQuestionMagPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.HgQuestionMagPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.hgquestionmagpanel',

    requires: [
        'CallCenterApp.view.HgQuestionMagPanelViewModel',
        'CallCenterApp.view.HgQuestionMagPanelViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.View',
        'Ext.selection.RowModel',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    controller: 'hgquestionmagpanel',
    viewModel: {
        type: 'hgquestionmagpanel'
    },
    height: 523,
    id: 'HgQuestionMagPanel',
    itemId: 'HgQuestionMagPanel',
    width: 736,
    layout: 'border',
    closable: true,
    title: '咨询管理',

    items: [
        {
            xtype: 'gridpanel',
            flex: 2,
            region: 'west',
            split: true,
            itemId: 'QuestionCustGridPanel',
            width: 150,
            title: '客户列表',
            store: 'QuestionCustStore',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 56,
                    align: 'center',
                    dataIndex: 'string',
                    text: '序号'
                },
                {
                    xtype: 'gridcolumn',
                    width: 143,
                    align: 'center',
                    dataIndex: 'f_name',
                    text: '客户姓名'
                },
                {
                    xtype: 'gridcolumn',
                    width: 164,
                    align: 'center',
                    dataIndex: 'f_phone',
                    text: '联系方式'
                }
            ],
            listeners: {
                render: 'onQuestionCustGridPanelRender',
                rowclick: 'onQuestionCustGridPanelRowClick'
            },
            selModel: {
                selType: 'rowmodel',
                mode: 'SINGLE'
            }
        },
        {
            xtype: 'panel',
            flex: 4,
            region: 'center',
            split: false,
            autoScroll: true,
            itemId: 'HgQuesttionContainer',
            title: '消息窗口',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textareafield',
                    flex: 1,
                    itemId: 'QuestionDetalArea',
                    overflowX: 'scroll',
                    overflowY: 'scroll',
                    fieldLabel: ''
                },
                {
                    xtype: 'panel',
                    height: 154,
                    itemId: 'contentSubmitPanel',
                    width: 530,
                    title: '',
                    items: [
                        {
                            xtype: 'textareafield',
                            height: 115,
                            itemId: 'ReplyContentField',
                            width: 572,
                            fieldLabel: '回复内容',
                            labelWidth: 70
                        },
                        {
                            xtype: 'button',
                            itemId: 'ReplySubmitBtn',
                            margin: '0 0 0 100',
                            width: 56,
                            text: '提交',
                            listeners: {
                                click: 'onReplySubmitBtnClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});