/*
 * File: app/view/HgStatusPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.HgStatusPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.hgstpanel',

    requires: [
        'CallCenterApp.view.HgStatusPanelViewModel',
        'CallCenterApp.view.HgStatusPanelViewController',
        'Ext.toolbar.Paging',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.view.Table',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.property.Grid',
        'Ext.button.Button',
        'Ext.toolbar.Separator'
    ],

    controller: 'hgstatuspanel',
    viewModel: {
        type: 'hgstatuspanel'
    },
    height: 573,
    id: 'hgStatusPanel',
    itemId: 'hgStatusPanel',
    width: 718,
    layout: 'fit',
    closable: true,
    title: '融资状态查询',

    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'HgStatusStore'
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    itemId: 'refreshBtn',
                    text: '刷新',
                    listeners: {
                        click: 'onRefreshBtnClick'
                    }
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    itemId: 'exportBtn',
                    text: '导出内容',
                    listeners: {
                        click: 'onExportBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'detailBtn',
                    text: '详细信息',
                    listeners: {
                        click: 'onDetailBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'submitBtn',
                    text: '提交申请',
                    listeners: {
                        click: 'onSubmitBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'saveBtn',
                    text: '修改保存',
                    listeners: {
                        click: 'onSaveBtnClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'container',
            border: 5,
            layout: 'border',
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 12,
                    region: 'center',
                    split: false,
                    autoScroll: true,
                    frame: true,
                    itemId: 'StatusGridPanel',
                    title: '',
                    columnLines: true,
                    store: 'HgStatusStore',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 50,
                            align: 'center',
                            dataIndex: 'index',
                            text: '序号'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'f_ciid',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 122,
                            align: 'center',
                            dataIndex: 'name',
                            text: '姓名'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 130,
                            align: 'center',
                            dataIndex: 'phone',
                            text: '电话'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function (value, metaData, record, rowIndex, colIndex, store, view) {
                                if (value === 0) {
                                    return "待处理";
                                } else if (value === 1) {
                                    return "处理中";
                                } else if (value === 2) {
                                    return "已接受";
                                } else if (value === 3) {
                                    return "被驳回";
                                } else if (value === 4) {
                                    return "已出单";
                                } else if (value === 5) {
                                    return "已送单";
                                } else if (value === 6) {
                                    return "业务完成";
                                } else if (value === 7) {
                                    return "完成咨询";
                                }
                            },
                            width: 81,
                            align: 'center',
                            dataIndex: 'f_status',
                            text: '状态',
                            editor: {
                                xtype: 'combobox',
                                itemId: 'HgStatusComboBox',
                                editable: false,
                                displayField: 'name',
                                store: 'StatusStore',
                                valueField: 'id'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 154,
                            align: 'center',
                            dataIndex: 'appletime',
                            text: '提交时间'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 94,
                            align: 'center',
                            dataIndex: 'source',
                            text: '来源'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 122,
                            dataIndex: 'f_price',
                            text: '融资金额',
                            editor: {
                                xtype: 'numberfield',
                                itemId: 'HgpriceEditer',
                                minValue: 0
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 120,
                            dataIndex: 'f_desc',
                            text: '备注',
                            editor: {
                                xtype: 'textfield',
                                itemId: 'hgDescEditor'
                            }
                        }
                    ],
                    viewConfig: {
                        xtype: 'tableview',
                        enableTextSelection: true
                    },
                    listeners: {
                        rowdblclick: 'onStatusGridPanelRowDblClick',
                        cellcontextmenu: 'onStatusGridPanelCellContextMenu',
                        rowclick: 'onHgStatusGridPanelRowClick'
                    },
                    plugins: [
                        {
                            ptype: 'cellediting',
                            clicksToEdit: 1
                        }
                    ]
                },
                {
                    xtype: 'propertygrid',
                    flex: 3,
                    region: 'east',
                    split: true,
                    frame: true,
                    id: 'HgStatusPropertyPanel',
                    itemId: 'HgStatusPropertyPanel',
                    width: 150,
                    animCollapse: true,
                    collapsed: false,
                    collapsible: true,
                    title: '属性',
                    titleCollapse: true
                }
            ]
        }
    ],
    listeners: {
        render: 'onHgStatusPanelRender'
    }

});