/*
 * File: app/view/InsRequestPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.InsRequestPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.insrtpanel',

    requires: [
        'CallCenterApp.view.InsRequestPanelViewModel',
        'CallCenterApp.view.InsRequestPanelViewController',
        'Ext.form.field.Text',
        'Ext.container.Container',
        'Ext.button.Button'
    ],

    controller: 'insrequestpanel',
    viewModel: {
        type: 'insrequestpanel'
    },
    itemId: 'insRequestPanel',
    bodyPadding: 10,
    closable: true,
    title: '保险申请',

    items: [
        {
            xtype: 'textfield',
            itemId: 'nameField',
            margin: 10,
            width: 380,
            fieldLabel: '姓名',
            labelWidth: 60,
            allowBlank: false,
            emptyText: '必需填写'
        },
        {
            xtype: 'textfield',
            itemId: 'phoneField',
            margin: 10,
            width: 380,
            fieldLabel: '电话',
            labelWidth: 60,
            allowBlank: false,
            emptyText: '必需填写',
            regex: /^1(3|5|8)[0-9]{9}$/,
            regexText: '手机号码为11位'
        },
        {
            xtype: 'textfield',
            itemId: 'idCardField',
            margin: 10,
            width: 380,
            fieldLabel: '身份证',
            labelWidth: 60,
            allowBlank: false,
            emptyText: '必需填写',
            regex: /(^\d{15}$)|(^\d{17}([0-9]|X)$)/,
            regexText: '中国的身份证为15位或18(加上X)位'
        },
        {
            xtype: 'textfield',
            itemId: 'plateNumField',
            margin: 10,
            width: 380,
            fieldLabel: '车牌号',
            labelWidth: 60,
            allowBlank: false,
            emptyText: '必需填写',
            regex: /^[\u4e00-\u9fa5]{1}[A-Z]{1}[A-Z_0-9]{5}$/,
            regexText: '车牌号为省份简称加字母数字'
        },
        {
            xtype: 'textfield',
            itemId: 'engineNumField',
            margin: 10,
            width: 380,
            fieldLabel: '发动机号',
            labelWidth: 60,
            allowBlank: false,
            emptyText: '必需填写'
        },
        {
            xtype: 'textfield',
            itemId: 'descField',
            margin: 10,
            width: 380,
            fieldLabel: '备注',
            labelWidth: 60
        },
        {
            xtype: 'container',
            layout: 'absolute',
            items: [
                {
                    xtype: 'button',
                    x: 260,
                    y: 10,
                    height: 35,
                    itemId: 'submitBtn',
                    width: 100,
                    text: '提交资料',
                    listeners: {
                        click: 'onSubmitBtnClick'
                    }
                }
            ]
        }
    ]

});