/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'CallCenterApp.view.MainViewViewModel',
        'CallCenterApp.view.MainViewViewController',
        'Ext.tab.Panel'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    id: 'mainView',
    itemId: 'mainView',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 100,
            hidden: true,
            itemId: 'headerPanel',
            title: '呼叫中心业务系统'
        },
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            autoScroll: true,
            itemId: 'menuPanel',
            width: 250,
            layout: 'accordion',
            animCollapse: true,
            collapseDirection: 'left',
            collapsed: false,
            collapsible: true,
            iconCls: 'Magnifierzoomin',
            title: '导航',
            titleCollapse: true,
            listeners: {
                render: 'onMenuPanelRender'
            }
        },
        {
            xtype: 'tabpanel',
            flex: 1,
            region: 'center',
            itemId: 'contentPanel',
            title: ''
        },
        {
            xtype: 'panel',
            region: 'south',
            height: 80,
            hidden: true,
            itemId: 'footerPanel',
            title: 'Footer'
        }
    ],
    listeners: {
        afterrender: 'onMainViewAfterRender'
    }

});