/*
 * File: app/view/sqdBusiness.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.sqdBusiness', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sqdbusiness',

    requires: [
        'CallCenterApp.view.sqdBusinessViewModel',
        'CallCenterApp.view.sqdBusinessViewController',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    controller: 'sqdbusiness',
    viewModel: {
        type: 'sqdbusiness'
    },
    itemId: 'sqdBusiness',
    title: '社区店业务',

    items: [
        {
            xtype: 'menu',
            floating: false,
            hidden: false,
            itemId: 'menuSqd',
            items: [
                {
                    xtype: 'menuitem',
                    itemId: 'sqdRequestItem',
                    text: '服务预约'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'sqdStatusItem',
                    text: '预约查询'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'sqdCallbackItem',
                    text: '回访列表'
                }
            ],
            listeners: {
                click: 'onMenuSqdClick'
            }
        }
    ]

});