/*
 * File: app/view/SubmitWindowViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.SubmitWindowViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.submitwindow',

    onDeptGridPanelSelectionChange: function (model, selected, eOpts) {
        if (selected.length === 1) {
            var bizManStore = Ext.getStore('BizManStore');
            var ajaxProxy = bizManStore.getProxy();
            var url = Ext.getStore('ConfigStore').getAt(0).get('WebServerUrl');
            ajaxProxy.setUrl(url + "/action/hg/bizman.do?deptId=" + selected[0].id);
            bizManStore.load();
        } else {
            bizManStore.removeAll();
        }
    },

    onSubmitBtnClick: function (button, e, eOpts) {
        var hgSubmitWindow = Ext.getCmp('hgSubmitWindow');
        var bizManGrid = hgSubmitWindow.down('#bizManGridPanel');

        if (bizManGrid.selection === null) {
            Ext.Msg.alert('错误', '请选择要分配的业务员');
            return;
        }

        var url = Ext.getStore('ConfigStore').getAt(0).get('WebServerUrl');
        Ext.Ajax.request({
            url: url + '/action/hg/accept.do',
            params: {
                id: hgSubmitWindow.requestId,
                bizman: bizManGrid.selection.data.phone
            },

            success: function (response) {
                var text = response.responseText;
                var result = JSON.parse(text);

                if (result === null) {
                    Ext.Msg.alert('提示', '申请提交出错了，结果：' + text);
                    return;
                }

                if (result.errCode === 0) {
                    Ext.Msg.alert('提示', '申请提交成功');
                } else {
                    Ext.Msg.alert('提示', '申请提交出错了，错误：' + result.errMsg);
                }
            }
        });

    }

});
