/*
 * File: app/view/syRentBusiness.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.syRentBusiness', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.syrentbusiness',

    requires: [
        'CallCenterApp.view.syRentBusinessViewModel'
    ],

    viewModel: {
        type: 'syrentbusiness'
    },
    itemId: 'syRentBusiness',
    title: '随易租车业务'

});