/*
 * File: app/view/systemOprateAdminViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.systemOprateAdminViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.systemoprateadmin',

    onSystemOprateMenuClick: function (menu, item, e, eOpts) {
        var mainView = Ext.getCmp('mainView');
        var contentPanel = mainView.getComponent('contentPanel');

        if (item.itemId == 'authorityManager') {
            var AuthorityManagerPanel = contentPanel.getComponent('AuthorityManagerPanel');

            if (AuthorityManagerPanel === undefined) {
                AuthorityManagerPanel = new CallCenterApp.view.AuthorityManagerPanel({});

                contentPanel.add(AuthorityManagerPanel);
            }

            contentPanel.setActiveTab(AuthorityManagerPanel);

        } else if (item.itemId == 'businessSystemManager') {
            var BusinessSystemManagerPanel = contentPanel.getComponent('BusinessSystemManagerPanel');

            if (BusinessSystemManagerPanel === undefined) {
                BusinessSystemManagerPanel = new CallCenterApp.view.BusinessSystemManagerPanel({});

                contentPanel.add(BusinessSystemManagerPanel);
            }

            contentPanel.setActiveTab(BusinessSystemManagerPanel);
        }
    }

});
