/*
 * File: app/view/xcBusiness.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.view.xcBusiness', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.xcbusiness',

    requires: [
        'CallCenterApp.view.xcBusinessViewModel',
        'CallCenterApp.view.xcBusinessViewController',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    controller: 'xcbusiness',
    viewModel: {
        type: 'xcbusiness'
    },
    itemId: 'xcBusiness',
    title: '讯畅业务',

    items: [
        {
            xtype: 'menu',
            floating: false,
            hidden: false,
            itemId: 'menuXc',
            items: [
                {
                    xtype: 'menuitem',
                    itemId: 'xcRequestItem',
                    text: '开卡申请'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'xcStatusItem',
                    text: '申请查询'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'xcRecordItem',
                    text: '流水查询'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'xcBalanceItem',
                    hideOnClick: false,
                    text: '余额查询'
                }
            ],
            listeners: {
                click: 'onMenuXcClick'
            }
        }
    ]

});