/*
 * File: app/store/EticketTypeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.store.EticketTypeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.String'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'EticketTypeStore',
            data: [
                {
                    id: '普通券',
                    name: '普通券'
                },
                {
                    id: '折扣券',
                    name: '折扣券'
                },
                {
                    id: '代金券',
                    name: '代金券'
                }
            ],
            fields: [
                {
                    type: 'string',
                    name: 'id'
                },
                {
                    type: 'string',
                    name: 'name'
                }
            ]
        }, cfg)]);
    }
});