package com.order.data.mapper;

import com.order.data.model.TaskDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TaskDetailMapper {
    List<TaskDetail> getClickedTaskDetailInfo(Map<String,Object> params);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_detail
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    int countByExample(TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_detail
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    int deleteByExample(TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_detail
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_detail
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    int insert(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_detail
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    int insertSelective(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_detail
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    List<TaskDetail> selectByExample(TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_detail
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    TaskDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_detail
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") TaskDetail record, @Param("example") TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_detail
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    int updateByExample(@Param("record") TaskDetail record, @Param("example") TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_detail
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    int updateByPrimaryKeySelective(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_detail
     *
     * @mbggenerated Fri Jul 01 20:48:30 CST 2016
     */
    int updateByPrimaryKey(TaskDetail record);
}