package com.order.data.mapper;

import com.order.data.model.TaskInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TaskInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbggenerated Fri Jul 01 20:42:28 CST 2016
     */
    int countByExample(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbggenerated Fri Jul 01 20:42:28 CST 2016
     */
    int deleteByExample(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbggenerated Fri Jul 01 20:42:28 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbggenerated Fri Jul 01 20:42:28 CST 2016
     */
    int insert(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbggenerated Fri Jul 01 20:42:28 CST 2016
     */
    int insertSelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbggenerated Fri Jul 01 20:42:28 CST 2016
     */
    List<TaskInfo> selectByExample(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbggenerated Fri Jul 01 20:42:28 CST 2016
     */
    TaskInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbggenerated Fri Jul 01 20:42:28 CST 2016
     */
    int updateByExampleSelective(@Param("record") TaskInfo record, @Param("example") TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbggenerated Fri Jul 01 20:42:28 CST 2016
     */
    int updateByExample(@Param("record") TaskInfo record, @Param("example") TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbggenerated Fri Jul 01 20:42:28 CST 2016
     */
    int updateByPrimaryKeySelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbggenerated Fri Jul 01 20:42:28 CST 2016
     */
    int updateByPrimaryKey(TaskInfo record);
}