/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('platformApp.view.MainView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainview',

    requires: [
        'Ext.Panel',
        'Ext.Button',
        'Ext.Audio'
    ],

    config: {
        layout: {
            type: 'card',
            animation: 'scroll'
        },
        items: [
            {
                xtype: 'panel',
                itemId: 'homePanel',
                layout: 'fit',
                items: [
                    {
                        xtype: 'panel',
                        itemId: 'loginPanel',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'showLoginButton',
                                margin: 20,
                                padding: 8,
                                text: '登录'
                            },
                            {
                                xtype: 'button',
                                itemId: 'showRegisterButton',
                                margin: 20,
                                padding: 8,
                                text: '注册'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        hidden: true,
                        itemId: 'welcomePanel',
                        items: [
                            {
                                xtype: 'audio',
                                id: 'audioPlay',
                                itemId: 'audioPlay',
                                autoPause: false,
                                enableControls: true,
                                url: 'resources/cl.mp3'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});