/*
 * File: app/store/StatusStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CallCenterApp.store.StatusStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'StatusStore',
            data: [
                {
                    id: 0,
                    name: '待处理'
                },
                {
                    id: 1,
                    name: '处理中'
                },
                {
                    id: 2,
                    name: '已接受'
                },
                {
                    id: 3,
                    name: '被驳回'
                },
                {
                    id: 4,
                    name: '已出单'
                },
                {
                    id: 5,
                    name: '已送单'
                },
                {
                    id: 6,
                    name: '业务完成'
                },
                {
                    id: 7,
                    name: '完成咨询'
                }
            ],
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'name'
                }
            ]
        }, cfg)]);
    }
});